export type Status = "preorder_open" | "preorder_closing" | "coming_soon";
export type RetailerColor = "blue" | "pink" | "teal" | "purple" | "gold";

export interface Figure {
  id: string;
  name: string;
  series: string;
  manufacturer: string;
  type: string;
  price_jpy: number;
  price_usd: number;
  retailer: string;
  retailer_color: RetailerColor;
  status: Status;
  quantity: number;
  availability: string;
  release_date: string;
  scale: string;
  height: string;
  featured: boolean;
  image_url: string;
  images: string[];
}

export const RETAILER_COLORS: Record<RetailerColor, string> = {
  blue: "#4DA8FF",
  pink: "#E8629A",
  teal: "#3DE8C8",
  purple: "#9B6FE8",
  gold: "#F0C060",
};

export const TYPES = [
  "All",
  "Scale",
  "Nendoroid",
  "Figma",
  "SH Figuarts",
  "Pop Up Parade",
  "Bunny Ver.",
];

// Scraped from hobby-genki.com (pre-order listing + each product's detail page).
// Real from the source: name, price_jpy, retailer, manufacturer, series, scale,
// height, release_date (the product's `available_date`), and all gallery images.
export const figures: Figure[] = [
  {
    id: "1",
    name: "Megurine Luka V4X Nendoroid (Ltd. Bonus Set)",
    series: "Vocaloid",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 8750,
    price_usd: 60,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-11-30",
    scale: "Non-scale",
    height: "10cm",
    featured: true,
    quantity: 58,
    availability: "available",
    image_url: "/figures/luka-v4x/thumb.jpg",
    images: [
      "/figures/luka-v4x/01.jpg",
      "/figures/luka-v4x/02.jpg",
      "/figures/luka-v4x/03.jpg",
      "/figures/luka-v4x/04.jpg",
      "/figures/luka-v4x/05.jpg",
      "/figures/luka-v4x/06.jpg",
      "/figures/luka-v4x/07.jpg",
    ],
  },
  {
    id: "2",
    name: "Cats are Liquid: Silver Moon",
    series: "Cats are Liquid (Karaage Toufu)",
    manufacturer: "WE ART DOING",
    type: "Scale",
    price_jpy: 39990,
    price_usd: 272,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "Non-scale",
    height: "19.2cm",
    featured: false,
    quantity: 1,
    availability: "last_remaining_items",
    image_url: "/figures/cats-silver-moon/thumb.jpg",
    images: [
      "/figures/cats-silver-moon/01.jpg",
      "/figures/cats-silver-moon/02.jpg",
      "/figures/cats-silver-moon/03.jpg",
      "/figures/cats-silver-moon/04.jpg",
      "/figures/cats-silver-moon/05.jpg",
      "/figures/cats-silver-moon/06.jpg",
      "/figures/cats-silver-moon/07.jpg",
      "/figures/cats-silver-moon/08.jpg",
      "/figures/cats-silver-moon/09.jpg",
      "/figures/cats-silver-moon/10.jpg",
      "/figures/cats-silver-moon/11.jpg",
      "/figures/cats-silver-moon/12.jpg",
      "/figures/cats-silver-moon/13.jpg",
    ],
  },
  {
    id: "3",
    name: "Cats are Liquid: Scarlet Night",
    series: "Cats are Liquid (Karaage Toufu)",
    manufacturer: "WE ART DOING",
    type: "Scale",
    price_jpy: 39990,
    price_usd: 272,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "Non-scale",
    height: "19.2cm",
    featured: false,
    quantity: 1,
    availability: "last_remaining_items",
    image_url: "/figures/cats-scarlet-night/thumb.jpg",
    images: [
      "/figures/cats-scarlet-night/01.jpg",
      "/figures/cats-scarlet-night/02.jpg",
      "/figures/cats-scarlet-night/03.jpg",
      "/figures/cats-scarlet-night/04.jpg",
      "/figures/cats-scarlet-night/05.jpg",
      "/figures/cats-scarlet-night/06.jpg",
      "/figures/cats-scarlet-night/07.jpg",
      "/figures/cats-scarlet-night/08.jpg",
      "/figures/cats-scarlet-night/09.jpg",
      "/figures/cats-scarlet-night/10.jpg",
      "/figures/cats-scarlet-night/11.jpg",
      "/figures/cats-scarlet-night/12.jpg",
      "/figures/cats-scarlet-night/13.jpg",
    ],
  },
  {
    id: "4",
    name: "Pokémon Scale World Sinnoh Region (3 set)",
    series: "Pokémon",
    manufacturer: "Bandai",
    type: "Scale",
    price_jpy: 4488,
    price_usd: 31,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-10-31",
    scale: "1/20",
    height: "—",
    featured: false,
    quantity: 167,
    availability: "available",
    image_url: "/figures/pokemon-scale-world-sinnoh/thumb.jpg",
    images: [
      "/figures/pokemon-scale-world-sinnoh/01.jpg",
      "/figures/pokemon-scale-world-sinnoh/02.jpg",
      "/figures/pokemon-scale-world-sinnoh/03.jpg",
      "/figures/pokemon-scale-world-sinnoh/04.jpg",
      "/figures/pokemon-scale-world-sinnoh/05.jpg",
      "/figures/pokemon-scale-world-sinnoh/06.jpg",
    ],
  },
  {
    id: "5",
    name: "Toshiya Miyata Nendoroid (Ltd. Edition)",
    series: "Kis-My-Ft2",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 9490,
    price_usd: 65,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-01-31",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    quantity: 60,
    availability: "available",
    image_url: "/figures/toshiya-miyata/thumb.jpg",
    images: [
      "/figures/toshiya-miyata/01.jpg",
      "/figures/toshiya-miyata/02.jpg",
      "/figures/toshiya-miyata/03.jpg",
      "/figures/toshiya-miyata/04.jpg",
      "/figures/toshiya-miyata/05.jpg",
      "/figures/toshiya-miyata/06.jpg",
      "/figures/toshiya-miyata/07.jpg",
      "/figures/toshiya-miyata/08.jpg",
    ],
  },
  {
    id: "6",
    name: "B-Robo Kabutack RE: Super Change Cobrander Figure",
    series: "B-Robo Kabutack",
    manufacturer: "Bandai",
    type: "Figure",
    price_jpy: 4990,
    price_usd: 34,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-10-31",
    scale: "—",
    height: "16cm",
    featured: false,
    quantity: 11,
    availability: "available",
    image_url: "/figures/b-robo-kabutack-re/thumb.jpg",
    images: [
      "/figures/b-robo-kabutack-re/01.jpg",
      "/figures/b-robo-kabutack-re/02.jpg",
      "/figures/b-robo-kabutack-re/03.jpg",
      "/figures/b-robo-kabutack-re/04.jpg",
      "/figures/b-robo-kabutack-re/05.jpg",
      "/figures/b-robo-kabutack-re/06.jpg",
    ],
  },
  {
    id: "7",
    name: "HG 1/35 Zi-Artemis CODE GEASS Rozé of the Recapture Plastic Model",
    series: "Code Geass",
    manufacturer: "Bandai Spirits",
    type: "Model Kit",
    price_jpy: 10890,
    price_usd: 74,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-07-31",
    scale: "1/35",
    height: "—",
    featured: false,
    quantity: 0,
    availability: "unavailable",
    image_url: "/figures/hg-135-zi-artemis/01.jpg",
    images: [
      "/figures/hg-135-zi-artemis/01.jpg",
      "/figures/hg-135-zi-artemis/02.jpg",
      "/figures/hg-135-zi-artemis/03.jpg",
      "/figures/hg-135-zi-artemis/04.jpg",
      "/figures/hg-135-zi-artemis/05.jpg",
      "/figures/hg-135-zi-artemis/06.jpg",
      "/figures/hg-135-zi-artemis/07.jpg",
      "/figures/hg-135-zi-artemis/08.jpg",
    ],
  },
  {
    id: "8",
    name: "B-Robo Kabutack RE: Super Change Ganiran Figure",
    series: "B-Robo Kabutack",
    manufacturer: "Bandai",
    type: "Figure",
    price_jpy: 4990,
    price_usd: 34,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-10-31",
    scale: "—",
    height: "16cm",
    featured: false,
    quantity: 11,
    availability: "available",
    image_url: "/figures/b-robo-kabutack-re-x/01.jpg",
    images: [
      "/figures/b-robo-kabutack-re-x/01.jpg",
      "/figures/b-robo-kabutack-re-x/02.jpg",
      "/figures/b-robo-kabutack-re-x/03.jpg",
      "/figures/b-robo-kabutack-re-x/04.jpg",
      "/figures/b-robo-kabutack-re-x/05.jpg",
    ],
  },
  {
    id: "9",
    name: "MODEROID Miniature Combining & Transforming Ideon - Space Runaway Ideon Plastic Model",
    series: "Space Runaway Ideon",
    manufacturer: "Good Smile Company",
    type: "Model Kit",
    price_jpy: 3564,
    price_usd: 24,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-11-30",
    scale: "Non-scale",
    height: "13cm",
    featured: false,
    quantity: 194,
    availability: "available",
    image_url: "/figures/moderoid-miniature-combining-transforming/thumb.jpg",
    images: [
      "/figures/moderoid-miniature-combining-transforming/01.jpg",
      "/figures/moderoid-miniature-combining-transforming/02.jpg",
      "/figures/moderoid-miniature-combining-transforming/03.jpg",
      "/figures/moderoid-miniature-combining-transforming/04.jpg",
      "/figures/moderoid-miniature-combining-transforming/05.jpg",
      "/figures/moderoid-miniature-combining-transforming/06.jpg",
      "/figures/moderoid-miniature-combining-transforming/07.jpg",
      "/figures/moderoid-miniature-combining-transforming/08.jpg",
    ],
  },
  {
    id: "10",
    name: "MODEROID Miniature Combining & Transforming Getter Dragon - Getter Robo G Plastic Model",
    series: "Getter Robo G",
    manufacturer: "Good Smile Company",
    type: "Model Kit",
    price_jpy: 3159,
    price_usd: 21,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-11-30",
    scale: "Non-scale",
    height: "12cm",
    featured: false,
    quantity: 193,
    availability: "available",
    image_url: "/figures/moderoid-miniature-combining-transforming-x/thumb.jpg",
    images: [
      "/figures/moderoid-miniature-combining-transforming-x/01.jpg",
      "/figures/moderoid-miniature-combining-transforming-x/02.jpg",
      "/figures/moderoid-miniature-combining-transforming-x/03.jpg",
      "/figures/moderoid-miniature-combining-transforming-x/04.jpg",
      "/figures/moderoid-miniature-combining-transforming-x/05.jpg",
      "/figures/moderoid-miniature-combining-transforming-x/06.jpg",
      "/figures/moderoid-miniature-combining-transforming-x/07.jpg",
      "/figures/moderoid-miniature-combining-transforming-x/08.jpg",
    ],
  },
  {
    id: "11",
    name: "Nendoroid Hakos Baelz - hololive production Figure Limited Edition",
    series: "Hololive",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 9980,
    price_usd: 68,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-01-31",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    quantity: 56,
    availability: "available",
    image_url: "/figures/nendoroid-hakos-baelz-hololive/thumb.jpg",
    images: [
      "/figures/nendoroid-hakos-baelz-hololive/01.jpg",
      "/figures/nendoroid-hakos-baelz-hololive/02.jpg",
      "/figures/nendoroid-hakos-baelz-hololive/03.jpg",
      "/figures/nendoroid-hakos-baelz-hololive/04.jpg",
      "/figures/nendoroid-hakos-baelz-hololive/05.jpg",
      "/figures/nendoroid-hakos-baelz-hololive/06.jpg",
      "/figures/nendoroid-hakos-baelz-hololive/07.jpg",
    ],
  },
  {
    id: "12",
    name: "Nendoroid Hatsune Miku V4X Figure Reissue",
    series: "Vocaloid",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 5934,
    price_usd: 40,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-11-30",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    quantity: 198,
    availability: "available",
    image_url: "/figures/nendoroid-hatsune-miku-v4x/thumb.jpg",
    images: [
      "/figures/nendoroid-hatsune-miku-v4x/01.jpg",
      "/figures/nendoroid-hatsune-miku-v4x/02.jpg",
      "/figures/nendoroid-hatsune-miku-v4x/03.jpg",
      "/figures/nendoroid-hatsune-miku-v4x/04.jpg",
      "/figures/nendoroid-hatsune-miku-v4x/05.jpg",
      "/figures/nendoroid-hatsune-miku-v4x/06.jpg",
      "/figures/nendoroid-hatsune-miku-v4x/07.jpg",
    ],
  },
  {
    id: "13",
    name: "Kaho Hinoshita Love Live! Hasunosora Girls' High School Idol Club 1/7 Scale Figure",
    series: "Love Live! Hasunosora",
    manufacturer: "Royce Entertainment",
    type: "Scale",
    price_jpy: 20273,
    price_usd: 138,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "1/7",
    height: "22cm",
    featured: false,
    quantity: 200,
    availability: "available",
    image_url: "/figures/kaho-hinoshita-love-live/thumb.jpg",
    images: [
      "/figures/kaho-hinoshita-love-live/01.jpg",
      "/figures/kaho-hinoshita-love-live/02.jpg",
      "/figures/kaho-hinoshita-love-live/03.jpg",
      "/figures/kaho-hinoshita-love-live/04.jpg",
      "/figures/kaho-hinoshita-love-live/05.jpg",
      "/figures/kaho-hinoshita-love-live/06.jpg",
      "/figures/kaho-hinoshita-love-live/07.jpg",
      "/figures/kaho-hinoshita-love-live/08.jpg",
    ],
  },
  {
    id: "14",
    name: "Sayaka Murano Love Live! Hasunosora Girls' High School Idol Club 1/7 Scale Figure",
    series: "Love Live! Hasunosora",
    manufacturer: "Royce Entertainment",
    type: "Scale",
    price_jpy: 20273,
    price_usd: 138,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "1/7",
    height: "23cm",
    featured: false,
    quantity: 200,
    availability: "available",
    image_url: "/figures/sayaka-murano-love-live/thumb.jpg",
    images: [
      "/figures/sayaka-murano-love-live/01.jpg",
      "/figures/sayaka-murano-love-live/02.jpg",
      "/figures/sayaka-murano-love-live/03.jpg",
      "/figures/sayaka-murano-love-live/04.jpg",
      "/figures/sayaka-murano-love-live/05.jpg",
      "/figures/sayaka-murano-love-live/06.jpg",
      "/figures/sayaka-murano-love-live/07.jpg",
      "/figures/sayaka-murano-love-live/08.jpg",
    ],
  },
  {
    id: "15",
    name: "Rurino Osawa Love Live! Hasunosora Girls' High School Idol Club 1/7 Scale Figure",
    series: "Love Live! Hasunosora",
    manufacturer: "Royce Entertainment",
    type: "Scale",
    price_jpy: 20273,
    price_usd: 138,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "1/7",
    height: "22cm",
    featured: false,
    quantity: 200,
    availability: "available",
    image_url: "/figures/rurino-osawa-love-love/thumb.jpg",
    images: [
      "/figures/rurino-osawa-love-love/01.jpg",
      "/figures/rurino-osawa-love-love/02.jpg",
      "/figures/rurino-osawa-love-love/03.jpg",
      "/figures/rurino-osawa-love-love/04.jpg",
      "/figures/rurino-osawa-love-love/05.jpg",
      "/figures/rurino-osawa-love-love/06.jpg",
      "/figures/rurino-osawa-love-love/07.jpg",
      "/figures/rurino-osawa-love-love/08.jpg",
    ],
  },
  {
    id: "16",
    name: "TENITOL TALL Rikka Takarada & Akane Shinjo Sports Wear Ver. Special Set Gridman Universe Figure",
    series: "Gridman Universe",
    manufacturer: "FuRyu",
    type: "Figure",
    price_jpy: 22990,
    price_usd: 156,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "—",
    height: "36cm",
    featured: false,
    quantity: 19,
    availability: "available",
    image_url: "/figures/tenitol-tall-rikka-takarada/thumb.jpg",
    images: [
      "/figures/tenitol-tall-rikka-takarada/01.jpg",
      "/figures/tenitol-tall-rikka-takarada/02.jpg",
      "/figures/tenitol-tall-rikka-takarada/03.jpg",
      "/figures/tenitol-tall-rikka-takarada/04.jpg",
      "/figures/tenitol-tall-rikka-takarada/05.jpg",
      "/figures/tenitol-tall-rikka-takarada/06.jpg",
      "/figures/tenitol-tall-rikka-takarada/07.jpg",
      "/figures/tenitol-tall-rikka-takarada/08.jpg",
    ],
  },
  {
    id: "17",
    name: "TENITOL TALL Akane Shinjo: Sports Wear Ver. Gridman Universe Figure",
    series: "Gridman Universe",
    manufacturer: "FuRyu",
    type: "Figure",
    price_jpy: 10137,
    price_usd: 69,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "Non-scale",
    height: "27.5cm",
    featured: false,
    quantity: 199,
    availability: "available",
    image_url: "/figures/tenitol-tall-akane-shinjo/thumb.jpg",
    images: [
      "/figures/tenitol-tall-akane-shinjo/01.jpg",
      "/figures/tenitol-tall-akane-shinjo/02.jpg",
      "/figures/tenitol-tall-akane-shinjo/03.jpg",
      "/figures/tenitol-tall-akane-shinjo/04.jpg",
      "/figures/tenitol-tall-akane-shinjo/05.jpg",
      "/figures/tenitol-tall-akane-shinjo/06.jpg",
      "/figures/tenitol-tall-akane-shinjo/07.jpg",
      "/figures/tenitol-tall-akane-shinjo/08.jpg",
    ],
  },
  {
    id: "18",
    name: "TENITOL TALL Rikka Takarada: Sports Wear Ver. Gridman Universe Figure",
    series: "Gridman Universe",
    manufacturer: "FuRyu",
    type: "Figure",
    price_jpy: 10137,
    price_usd: 69,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "Non-scale",
    height: "35.5cm",
    featured: false,
    quantity: 198,
    availability: "available",
    image_url: "/figures/tenitol-tall-rikka-takarada-x/thumb.jpg",
    images: [
      "/figures/tenitol-tall-rikka-takarada-x/01.jpg",
      "/figures/tenitol-tall-rikka-takarada-x/02.jpg",
      "/figures/tenitol-tall-rikka-takarada-x/03.jpg",
      "/figures/tenitol-tall-rikka-takarada-x/04.jpg",
      "/figures/tenitol-tall-rikka-takarada-x/05.jpg",
      "/figures/tenitol-tall-rikka-takarada-x/06.jpg",
      "/figures/tenitol-tall-rikka-takarada-x/07.jpg",
      "/figures/tenitol-tall-rikka-takarada-x/08.jpg",
    ],
  },
  {
    id: "19",
    name: "PalVerse Pale. Sonic the Hedgehog: Super Sonic Figure [Bushiroad Creative]",
    series: "Sonic the Hedgehog",
    manufacturer: "Bushiroad",
    type: "Figure",
    price_jpy: 2835,
    price_usd: 19,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-11-30",
    scale: "—",
    height: "13cm",
    featured: false,
    quantity: 192,
    availability: "available",
    image_url: "/figures/palverse-pale-sonic-the/01.jpg",
    images: [
      "/figures/palverse-pale-sonic-the/01.jpg",
      "/figures/palverse-pale-sonic-the/02.jpg",
      "/figures/palverse-pale-sonic-the/03.jpg",
      "/figures/palverse-pale-sonic-the/04.jpg",
    ],
  },
  {
    id: "20",
    name: "Nendoroid Kamui Gintama Figure",
    series: "Gintama",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 6708,
    price_usd: 46,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-12-31",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    quantity: 0,
    availability: "unavailable",
    image_url: "/figures/nendoroid-kamui-gintama-figure/thumb.jpg",
    images: [
      "/figures/nendoroid-kamui-gintama-figure/01.jpg",
      "/figures/nendoroid-kamui-gintama-figure/02.jpg",
      "/figures/nendoroid-kamui-gintama-figure/03.jpg",
      "/figures/nendoroid-kamui-gintama-figure/04.jpg",
      "/figures/nendoroid-kamui-gintama-figure/05.jpg",
    ],
  },
  {
    id: "21",
    name: "Nendoroid Shinsuke Takasugi Gintama Figure",
    series: "Gintama",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 6708,
    price_usd: 46,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-12-31",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    quantity: 0,
    availability: "unavailable",
    image_url: "/figures/nendoroid-shinsuke-takasugi-gintama/thumb.jpg",
    images: [
      "/figures/nendoroid-shinsuke-takasugi-gintama/01.jpg",
      "/figures/nendoroid-shinsuke-takasugi-gintama/02.jpg",
      "/figures/nendoroid-shinsuke-takasugi-gintama/03.jpg",
      "/figures/nendoroid-shinsuke-takasugi-gintama/04.jpg",
      "/figures/nendoroid-shinsuke-takasugi-gintama/05.jpg",
    ],
  },
  {
    id: "22",
    name: "Plafia Doala (Visitor Ver.) Plastic Model [PLUMPMOA]",
    series: "Doala",
    manufacturer: "PLUM",
    type: "Model Kit",
    price_jpy: 3828,
    price_usd: 26,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-08-31",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    quantity: 200,
    availability: "available",
    image_url: "/figures/plafia-doala-visitor-ver/thumb.jpg",
    images: [
      "/figures/plafia-doala-visitor-ver/01.jpg",
      "/figures/plafia-doala-visitor-ver/02.jpg",
      "/figures/plafia-doala-visitor-ver/03.jpg",
      "/figures/plafia-doala-visitor-ver/04.jpg",
      "/figures/plafia-doala-visitor-ver/05.jpg",
      "/figures/plafia-doala-visitor-ver/06.jpg",
      "/figures/plafia-doala-visitor-ver/07.jpg",
      "/figures/plafia-doala-visitor-ver/08.jpg",
    ],
  },
  {
    id: "23",
    name: "B-Style Mirajane Strauss: Bunny Ver. FAIRY TAIL 1/4 Scale Figure",
    series: "Fairy Tail",
    manufacturer: "FREEing",
    type: "Scale",
    price_jpy: 36575,
    price_usd: 249,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-12-31",
    scale: "1/4",
    height: "47cm",
    featured: false,
    quantity: 198,
    availability: "available",
    image_url: "/figures/b-style-mirajane-strauss/thumb.jpg",
    images: [
      "/figures/b-style-mirajane-strauss/01.jpg",
      "/figures/b-style-mirajane-strauss/02.jpg",
      "/figures/b-style-mirajane-strauss/03.jpg",
      "/figures/b-style-mirajane-strauss/04.jpg",
      "/figures/b-style-mirajane-strauss/05.jpg",
      "/figures/b-style-mirajane-strauss/06.jpg",
      "/figures/b-style-mirajane-strauss/07.jpg",
      "/figures/b-style-mirajane-strauss/08.jpg",
    ],
  },
  {
    id: "24",
    name: "Hatsune Miku: Music & Fire Works Ver. - Character Vocal Series 01: Hatsune 1/7 Scale Figure",
    series: "Vocaloid",
    manufacturer: "Good Smile Company",
    type: "Scale",
    price_jpy: 26410,
    price_usd: 180,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-06-30",
    scale: "1/7",
    height: "32cm",
    featured: false,
    quantity: 196,
    availability: "available",
    image_url: "/figures/hatsune-miku-music-fire/thumb.jpg",
    images: [
      "/figures/hatsune-miku-music-fire/01.jpg",
      "/figures/hatsune-miku-music-fire/02.jpg",
      "/figures/hatsune-miku-music-fire/03.jpg",
      "/figures/hatsune-miku-music-fire/04.jpg",
      "/figures/hatsune-miku-music-fire/05.jpg",
      "/figures/hatsune-miku-music-fire/06.jpg",
      "/figures/hatsune-miku-music-fire/07.jpg",
      "/figures/hatsune-miku-music-fire/08.jpg",
    ],
  },
  {
    id: "25",
    name: "Nendoroid Mahiru Shiina The Angel Next Door Spoils Me Rotten Figure Reissue",
    series: "The Angel Next Door",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 5848,
    price_usd: 40,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-01-31",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    quantity: 199,
    availability: "available",
    image_url: "/figures/nendoroid-mahiru-shiina-the/thumb.jpg",
    images: [
      "/figures/nendoroid-mahiru-shiina-the/01.jpg",
      "/figures/nendoroid-mahiru-shiina-the/02.jpg",
      "/figures/nendoroid-mahiru-shiina-the/03.jpg",
      "/figures/nendoroid-mahiru-shiina-the/04.jpg",
      "/figures/nendoroid-mahiru-shiina-the/05.jpg",
    ],
  },
];

export function getFigure(id: string): Figure | undefined {
  return figures.find((f) => f.id === id);
}

export function getFeatured(): Figure {
  return figures.find((f) => f.featured) ?? figures[0];
}

export function relatedBySeries(series: string, excludeId: string): Figure[] {
  return figures.filter((f) => f.series === series && f.id !== excludeId);
}

/** Parse a YYYY-MM-DD string as local midnight to avoid timezone day-shifts. */
export function parseDate(s: string): Date {
  return new Date(s + "T00:00:00");
}

export type StockLevel = "sold_out" | "last_items" | "low" | "in_stock";

/** Real stock state from HG's PrestaShop `quantity` / `availability`. */
export function stockLevel(f: Figure): StockLevel {
  if (f.quantity <= 0 || f.availability === "unavailable") return "sold_out";
  if (f.availability === "last_remaining_items" || f.quantity <= 3)
    return "last_items";
  if (f.quantity <= 20) return "low";
  return "in_stock";
}
