export type Status = "preorder_open" | "preorder_closing" | "coming_soon";
export type RetailerColor = "blue" | "pink" | "teal" | "purple" | "gold";

export interface Figure {
  id: string;
  name: string;
  jan: string; // JAN/EAN barcode (PrestaShop `reference`); "" when none (e.g. art toys)
  series: string;
  manufacturer: string;
  type: string;
  price_jpy: number;
  price_usd: number;
  retailer: string;
  retailer_color: RetailerColor;
  status: Status;
  quantity: number;
  availability: string;
  release_date: string;
  droppedAt: string; // ISO date (YYYY-MM-DD) the figure was added to FigDrop (scrape session)
  scale: string;
  height: string;
  featured: boolean;
  image_url: string;
  images: string[];
}

export const RETAILER_COLORS: Record<RetailerColor, string> = {
  blue: "#4DA8FF",
  pink: "#E8629A",
  teal: "#3DE8C8",
  purple: "#9B6FE8",
  gold: "#F0C060",
};

// Drops-page filter chips, by brand. Manufacturer strings are grouped into
// these via brandGroup() — prefix matching folds brand families (Bandai
// Spirits/MegaHouse → Bandai, Good Smile Arts Shanghai → Good Smile Company).
// Everything else falls into "Other".
export const BRANDS = [
  "All",
  "Good Smile Company",
  "Bandai",
  "Kotobukiya",
  "McFarlane",
  "Trick or Treat",
  "Hot Toys",
  "FuRyu",
  "Royce Entertainment",
  "Other",
];

export function brandGroup(manufacturer: string): string {
  const m = manufacturer;
  if (m.startsWith("Good Smile")) return "Good Smile Company";
  if (m.startsWith("Bandai")) return "Bandai";
  if (m === "Kotobukiya") return "Kotobukiya";
  if (m.startsWith("McFarlane")) return "McFarlane";
  if (m.startsWith("Trick or Treat")) return "Trick or Treat";
  if (m === "Hot Toys") return "Hot Toys";
  if (m === "FuRyu") return "FuRyu";
  if (m === "Royce Entertainment") return "Royce Entertainment";
  return "Other";
}

// Scraped from hobby-genki.com (pre-order listing + each product's detail page).
// Real from the source: name, price_jpy, retailer, manufacturer, series, scale,
// height, release_date (the product's `available_date`), and all gallery images.
export const figures: Figure[] = [
  {
    id: "1",
    droppedAt: "2026-06-20",
    name: "Megurine Luka V4X Nendoroid (Ltd. Bonus Set)",
    series: "Vocaloid",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 8750,
    price_usd: 60,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-11-30",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    quantity: 58,
    availability: "available",
    jan: "4570232587090",
    image_url: "/figures/luka-v4x/thumb.jpg",
    images: [
      "/figures/luka-v4x/01.jpg",
      "/figures/luka-v4x/02.jpg",
      "/figures/luka-v4x/03.jpg",
      "/figures/luka-v4x/04.jpg",
      "/figures/luka-v4x/05.jpg",
      "/figures/luka-v4x/06.jpg",
      "/figures/luka-v4x/07.jpg",
    ],
  },
  {
    id: "2",
    droppedAt: "2026-06-20",
    name: "Cats are Liquid: Silver Moon",
    series: "Cats are Liquid (Karaage Toufu)",
    manufacturer: "WE ART DOING",
    type: "Scale",
    price_jpy: 39990,
    price_usd: 272,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "Non-scale",
    height: "19.2cm",
    featured: false,
    quantity: 1,
    availability: "last_remaining_items",
    jan: "",
    image_url: "/figures/cats-silver-moon/thumb.jpg",
    images: [
      "/figures/cats-silver-moon/01.jpg",
      "/figures/cats-silver-moon/02.jpg",
      "/figures/cats-silver-moon/03.jpg",
      "/figures/cats-silver-moon/04.jpg",
      "/figures/cats-silver-moon/05.jpg",
      "/figures/cats-silver-moon/06.jpg",
      "/figures/cats-silver-moon/07.jpg",
      "/figures/cats-silver-moon/08.jpg",
      "/figures/cats-silver-moon/09.jpg",
      "/figures/cats-silver-moon/10.jpg",
      "/figures/cats-silver-moon/11.jpg",
      "/figures/cats-silver-moon/12.jpg",
      "/figures/cats-silver-moon/13.jpg",
    ],
  },
  {
    id: "3",
    droppedAt: "2026-06-20",
    name: "Cats are Liquid: Scarlet Night",
    series: "Cats are Liquid (Karaage Toufu)",
    manufacturer: "WE ART DOING",
    type: "Scale",
    price_jpy: 39990,
    price_usd: 272,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "Non-scale",
    height: "19.2cm",
    featured: false,
    quantity: 1,
    availability: "last_remaining_items",
    jan: "",
    image_url: "/figures/cats-scarlet-night/thumb.jpg",
    images: [
      "/figures/cats-scarlet-night/01.jpg",
      "/figures/cats-scarlet-night/02.jpg",
      "/figures/cats-scarlet-night/03.jpg",
      "/figures/cats-scarlet-night/04.jpg",
      "/figures/cats-scarlet-night/05.jpg",
      "/figures/cats-scarlet-night/06.jpg",
      "/figures/cats-scarlet-night/07.jpg",
      "/figures/cats-scarlet-night/08.jpg",
      "/figures/cats-scarlet-night/09.jpg",
      "/figures/cats-scarlet-night/10.jpg",
      "/figures/cats-scarlet-night/11.jpg",
      "/figures/cats-scarlet-night/12.jpg",
      "/figures/cats-scarlet-night/13.jpg",
    ],
  },
  {
    id: "4",
    droppedAt: "2026-06-20",
    name: "Pokémon Scale World Sinnoh Region (3 set)",
    series: "Pokémon",
    manufacturer: "Bandai",
    type: "Scale",
    price_jpy: 4488,
    price_usd: 31,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-10-31",
    scale: "1/20",
    height: "—",
    featured: false,
    quantity: 167,
    availability: "available",
    jan: "4570117928949",
    image_url: "/figures/pokemon-scale-world-sinnoh/thumb.jpg",
    images: [
      "/figures/pokemon-scale-world-sinnoh/01.jpg",
      "/figures/pokemon-scale-world-sinnoh/02.jpg",
      "/figures/pokemon-scale-world-sinnoh/03.jpg",
      "/figures/pokemon-scale-world-sinnoh/04.jpg",
      "/figures/pokemon-scale-world-sinnoh/05.jpg",
      "/figures/pokemon-scale-world-sinnoh/06.jpg",
    ],
  },
  {
    id: "5",
    droppedAt: "2026-06-20",
    name: "Toshiya Miyata Nendoroid (Ltd. Edition)",
    series: "Kis-My-Ft2",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 9490,
    price_usd: 65,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-01-31",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    quantity: 60,
    availability: "available",
    jan: "4570232587076",
    image_url: "/figures/toshiya-miyata/thumb.jpg",
    images: [
      "/figures/toshiya-miyata/01.jpg",
      "/figures/toshiya-miyata/02.jpg",
      "/figures/toshiya-miyata/03.jpg",
      "/figures/toshiya-miyata/04.jpg",
      "/figures/toshiya-miyata/05.jpg",
      "/figures/toshiya-miyata/06.jpg",
      "/figures/toshiya-miyata/07.jpg",
      "/figures/toshiya-miyata/08.jpg",
    ],
  },
  {
    id: "6",
    droppedAt: "2026-06-21",
    name: "B-Robo Kabutack RE: Super Change Cobrander Figure",
    series: "B-Robo Kabutack",
    manufacturer: "Bandai",
    type: "Figure",
    price_jpy: 4990,
    price_usd: 34,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-10-31",
    scale: "—",
    height: "16cm",
    featured: false,
    quantity: 11,
    availability: "available",
    jan: "4582770085129",
    image_url: "/figures/b-robo-kabutack-re/thumb.jpg",
    images: [
      "/figures/b-robo-kabutack-re/01.jpg",
      "/figures/b-robo-kabutack-re/02.jpg",
      "/figures/b-robo-kabutack-re/03.jpg",
      "/figures/b-robo-kabutack-re/04.jpg",
      "/figures/b-robo-kabutack-re/05.jpg",
      "/figures/b-robo-kabutack-re/06.jpg",
    ],
  },
  {
    id: "7",
    droppedAt: "2026-06-21",
    name: "HG 1/35 Zi-Artemis CODE GEASS Rozé of the Recapture Plastic Model",
    series: "Code Geass",
    manufacturer: "Bandai Spirits",
    type: "Model Kit",
    price_jpy: 10890,
    price_usd: 74,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-07-31",
    scale: "1/35",
    height: "—",
    featured: false,
    quantity: 0,
    availability: "unavailable",
    jan: "",
    image_url: "/figures/hg-135-zi-artemis/01.jpg",
    images: [
      "/figures/hg-135-zi-artemis/01.jpg",
      "/figures/hg-135-zi-artemis/02.jpg",
      "/figures/hg-135-zi-artemis/03.jpg",
      "/figures/hg-135-zi-artemis/04.jpg",
      "/figures/hg-135-zi-artemis/05.jpg",
      "/figures/hg-135-zi-artemis/06.jpg",
      "/figures/hg-135-zi-artemis/07.jpg",
      "/figures/hg-135-zi-artemis/08.jpg",
    ],
  },
  {
    id: "8",
    droppedAt: "2026-06-21",
    name: "B-Robo Kabutack RE: Super Change Ganiran Figure",
    series: "B-Robo Kabutack",
    manufacturer: "Bandai",
    type: "Figure",
    price_jpy: 4990,
    price_usd: 34,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-10-31",
    scale: "—",
    height: "16cm",
    featured: false,
    quantity: 11,
    availability: "available",
    jan: "4582770085136",
    image_url: "/figures/b-robo-kabutack-re-x/01.jpg",
    images: [
      "/figures/b-robo-kabutack-re-x/01.jpg",
      "/figures/b-robo-kabutack-re-x/02.jpg",
      "/figures/b-robo-kabutack-re-x/03.jpg",
      "/figures/b-robo-kabutack-re-x/04.jpg",
      "/figures/b-robo-kabutack-re-x/05.jpg",
    ],
  },
  {
    id: "9",
    droppedAt: "2026-06-21",
    name: "MODEROID Miniature Combining & Transforming Ideon - Space Runaway Ideon Plastic Model",
    series: "Space Runaway Ideon",
    manufacturer: "Good Smile Company",
    type: "Model Kit",
    price_jpy: 3564,
    price_usd: 24,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-11-30",
    scale: "Non-scale",
    height: "13cm",
    featured: false,
    quantity: 194,
    availability: "available",
    jan: "4570232587083",
    image_url: "/figures/moderoid-miniature-combining-transforming/thumb.jpg",
    images: [
      "/figures/moderoid-miniature-combining-transforming/01.jpg",
      "/figures/moderoid-miniature-combining-transforming/02.jpg",
      "/figures/moderoid-miniature-combining-transforming/03.jpg",
      "/figures/moderoid-miniature-combining-transforming/04.jpg",
      "/figures/moderoid-miniature-combining-transforming/05.jpg",
      "/figures/moderoid-miniature-combining-transforming/06.jpg",
      "/figures/moderoid-miniature-combining-transforming/07.jpg",
      "/figures/moderoid-miniature-combining-transforming/08.jpg",
    ],
  },
  {
    id: "10",
    droppedAt: "2026-06-21",
    name: "MODEROID Miniature Combining & Transforming Getter Dragon - Getter Robo G Plastic Model",
    series: "Getter Robo G",
    manufacturer: "Good Smile Company",
    type: "Model Kit",
    price_jpy: 3159,
    price_usd: 21,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-11-30",
    scale: "Non-scale",
    height: "12cm",
    featured: false,
    quantity: 193,
    availability: "available",
    jan: "4570232587069",
    image_url: "/figures/moderoid-miniature-combining-transforming-x/thumb.jpg",
    images: [
      "/figures/moderoid-miniature-combining-transforming-x/01.jpg",
      "/figures/moderoid-miniature-combining-transforming-x/02.jpg",
      "/figures/moderoid-miniature-combining-transforming-x/03.jpg",
      "/figures/moderoid-miniature-combining-transforming-x/04.jpg",
      "/figures/moderoid-miniature-combining-transforming-x/05.jpg",
      "/figures/moderoid-miniature-combining-transforming-x/06.jpg",
      "/figures/moderoid-miniature-combining-transforming-x/07.jpg",
      "/figures/moderoid-miniature-combining-transforming-x/08.jpg",
    ],
  },
  {
    id: "11",
    droppedAt: "2026-06-21",
    name: "Nendoroid Hakos Baelz - hololive production Figure Limited Edition",
    series: "Hololive Production",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 9980,
    price_usd: 68,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-01-31",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    quantity: 56,
    availability: "available",
    jan: "4570232587076",
    image_url: "/figures/nendoroid-hakos-baelz-hololive/thumb.jpg",
    images: [
      "/figures/nendoroid-hakos-baelz-hololive/01.jpg",
      "/figures/nendoroid-hakos-baelz-hololive/02.jpg",
      "/figures/nendoroid-hakos-baelz-hololive/03.jpg",
      "/figures/nendoroid-hakos-baelz-hololive/04.jpg",
      "/figures/nendoroid-hakos-baelz-hololive/05.jpg",
      "/figures/nendoroid-hakos-baelz-hololive/06.jpg",
      "/figures/nendoroid-hakos-baelz-hololive/07.jpg",
    ],
  },
  {
    id: "12",
    droppedAt: "2026-06-21",
    name: "Nendoroid Hatsune Miku V4X Figure Reissue",
    series: "Vocaloid",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 5934,
    price_usd: 40,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-11-30",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    quantity: 198,
    availability: "available",
    jan: "4570232585607",
    image_url: "/figures/nendoroid-hatsune-miku-v4x/thumb.jpg",
    images: [
      "/figures/nendoroid-hatsune-miku-v4x/01.jpg",
      "/figures/nendoroid-hatsune-miku-v4x/02.jpg",
      "/figures/nendoroid-hatsune-miku-v4x/03.jpg",
      "/figures/nendoroid-hatsune-miku-v4x/04.jpg",
      "/figures/nendoroid-hatsune-miku-v4x/05.jpg",
      "/figures/nendoroid-hatsune-miku-v4x/06.jpg",
      "/figures/nendoroid-hatsune-miku-v4x/07.jpg",
    ],
  },
  {
    id: "13",
    droppedAt: "2026-06-21",
    name: "Kaho Hinoshita Love Live! Hasunosora Girls' High School Idol Club 1/7 Scale Figure",
    series: "Love Live! Hasunosora",
    manufacturer: "Royce Entertainment",
    type: "Scale",
    price_jpy: 20273,
    price_usd: 138,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "1/7",
    height: "22cm",
    featured: false,
    quantity: 200,
    availability: "available",
    jan: "4571623518341",
    image_url: "/figures/kaho-hinoshita-love-live/thumb.jpg",
    images: [
      "/figures/kaho-hinoshita-love-live/01.jpg",
      "/figures/kaho-hinoshita-love-live/02.jpg",
      "/figures/kaho-hinoshita-love-live/03.jpg",
      "/figures/kaho-hinoshita-love-live/04.jpg",
      "/figures/kaho-hinoshita-love-live/05.jpg",
      "/figures/kaho-hinoshita-love-live/06.jpg",
      "/figures/kaho-hinoshita-love-live/07.jpg",
      "/figures/kaho-hinoshita-love-live/08.jpg",
    ],
  },
  {
    id: "14",
    droppedAt: "2026-06-21",
    name: "Sayaka Murano Love Live! Hasunosora Girls' High School Idol Club 1/7 Scale Figure",
    series: "Love Live! Hasunosora",
    manufacturer: "Royce Entertainment",
    type: "Scale",
    price_jpy: 20273,
    price_usd: 138,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "1/7",
    height: "23cm",
    featured: false,
    quantity: 200,
    availability: "available",
    jan: "4571623518358",
    image_url: "/figures/sayaka-murano-love-live/thumb.jpg",
    images: [
      "/figures/sayaka-murano-love-live/01.jpg",
      "/figures/sayaka-murano-love-live/02.jpg",
      "/figures/sayaka-murano-love-live/03.jpg",
      "/figures/sayaka-murano-love-live/04.jpg",
      "/figures/sayaka-murano-love-live/05.jpg",
      "/figures/sayaka-murano-love-live/06.jpg",
      "/figures/sayaka-murano-love-live/07.jpg",
      "/figures/sayaka-murano-love-live/08.jpg",
    ],
  },
  {
    id: "15",
    droppedAt: "2026-06-21",
    name: "Rurino Osawa Love Live! Hasunosora Girls' High School Idol Club 1/7 Scale Figure",
    series: "Love Live! Hasunosora",
    manufacturer: "Royce Entertainment",
    type: "Scale",
    price_jpy: 20273,
    price_usd: 138,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "1/7",
    height: "22cm",
    featured: false,
    quantity: 200,
    availability: "available",
    jan: "4571623518365",
    image_url: "/figures/rurino-osawa-love-love/thumb.jpg",
    images: [
      "/figures/rurino-osawa-love-love/01.jpg",
      "/figures/rurino-osawa-love-love/02.jpg",
      "/figures/rurino-osawa-love-love/03.jpg",
      "/figures/rurino-osawa-love-love/04.jpg",
      "/figures/rurino-osawa-love-love/05.jpg",
      "/figures/rurino-osawa-love-love/06.jpg",
      "/figures/rurino-osawa-love-love/07.jpg",
      "/figures/rurino-osawa-love-love/08.jpg",
    ],
  },
  {
    id: "16",
    droppedAt: "2026-06-21",
    name: "TENITOL TALL Rikka Takarada & Akane Shinjo Sports Wear Ver. Special Set Gridman Universe Figure",
    series: "Gridman Universe",
    manufacturer: "FuRyu",
    type: "Figure",
    price_jpy: 22990,
    price_usd: 156,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "—",
    height: "36cm",
    featured: false,
    quantity: 19,
    availability: "available",
    jan: "",
    image_url: "/figures/tenitol-tall-rikka-takarada/thumb.jpg",
    images: [
      "/figures/tenitol-tall-rikka-takarada/01.jpg",
      "/figures/tenitol-tall-rikka-takarada/02.jpg",
      "/figures/tenitol-tall-rikka-takarada/03.jpg",
      "/figures/tenitol-tall-rikka-takarada/04.jpg",
      "/figures/tenitol-tall-rikka-takarada/05.jpg",
      "/figures/tenitol-tall-rikka-takarada/06.jpg",
      "/figures/tenitol-tall-rikka-takarada/07.jpg",
      "/figures/tenitol-tall-rikka-takarada/08.jpg",
    ],
  },
  {
    id: "17",
    droppedAt: "2026-06-21",
    name: "TENITOL TALL Akane Shinjo: Sports Wear Ver. Gridman Universe Figure",
    series: "Gridman Universe",
    manufacturer: "FuRyu",
    type: "Figure",
    price_jpy: 10137,
    price_usd: 69,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "Non-scale",
    height: "27.5cm",
    featured: false,
    quantity: 199,
    availability: "available",
    jan: "4580736407770",
    image_url: "/figures/tenitol-tall-akane-shinjo/thumb.jpg",
    images: [
      "/figures/tenitol-tall-akane-shinjo/01.jpg",
      "/figures/tenitol-tall-akane-shinjo/02.jpg",
      "/figures/tenitol-tall-akane-shinjo/03.jpg",
      "/figures/tenitol-tall-akane-shinjo/04.jpg",
      "/figures/tenitol-tall-akane-shinjo/05.jpg",
      "/figures/tenitol-tall-akane-shinjo/06.jpg",
      "/figures/tenitol-tall-akane-shinjo/07.jpg",
      "/figures/tenitol-tall-akane-shinjo/08.jpg",
    ],
  },
  {
    id: "18",
    droppedAt: "2026-06-21",
    name: "TENITOL TALL Rikka Takarada: Sports Wear Ver. Gridman Universe Figure",
    series: "Gridman Universe",
    manufacturer: "FuRyu",
    type: "Figure",
    price_jpy: 10137,
    price_usd: 69,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-03-31",
    scale: "Non-scale",
    height: "35.5cm",
    featured: false,
    quantity: 198,
    availability: "available",
    jan: "4580736407787",
    image_url: "/figures/tenitol-tall-rikka-takarada-x/thumb.jpg",
    images: [
      "/figures/tenitol-tall-rikka-takarada-x/01.jpg",
      "/figures/tenitol-tall-rikka-takarada-x/02.jpg",
      "/figures/tenitol-tall-rikka-takarada-x/03.jpg",
      "/figures/tenitol-tall-rikka-takarada-x/04.jpg",
      "/figures/tenitol-tall-rikka-takarada-x/05.jpg",
      "/figures/tenitol-tall-rikka-takarada-x/06.jpg",
      "/figures/tenitol-tall-rikka-takarada-x/07.jpg",
      "/figures/tenitol-tall-rikka-takarada-x/08.jpg",
    ],
  },
  {
    id: "19",
    droppedAt: "2026-06-21",
    name: "PalVerse Pale. Sonic the Hedgehog: Super Sonic Figure [Bushiroad Creative]",
    series: "Sonic the Hedgehog",
    manufacturer: "Bushiroad",
    type: "Figure",
    price_jpy: 2835,
    price_usd: 19,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-11-30",
    scale: "—",
    height: "13cm",
    featured: false,
    quantity: 192,
    availability: "available",
    jan: "4570194458841",
    image_url: "/figures/palverse-pale-sonic-the/01.jpg",
    images: [
      "/figures/palverse-pale-sonic-the/01.jpg",
      "/figures/palverse-pale-sonic-the/02.jpg",
      "/figures/palverse-pale-sonic-the/03.jpg",
      "/figures/palverse-pale-sonic-the/04.jpg",
    ],
  },
  {
    id: "20",
    droppedAt: "2026-06-21",
    name: "Nendoroid Kamui Gintama Figure",
    series: "Gintama",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 6708,
    price_usd: 46,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-12-31",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    quantity: 0,
    availability: "unavailable",
    jan: "4570232584297",
    image_url: "/figures/nendoroid-kamui-gintama-figure/thumb.jpg",
    images: [
      "/figures/nendoroid-kamui-gintama-figure/01.jpg",
      "/figures/nendoroid-kamui-gintama-figure/02.jpg",
      "/figures/nendoroid-kamui-gintama-figure/03.jpg",
      "/figures/nendoroid-kamui-gintama-figure/04.jpg",
      "/figures/nendoroid-kamui-gintama-figure/05.jpg",
    ],
  },
  {
    id: "21",
    droppedAt: "2026-06-21",
    name: "Nendoroid Shinsuke Takasugi Gintama Figure",
    series: "Gintama",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 6708,
    price_usd: 46,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-12-31",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    quantity: 0,
    availability: "unavailable",
    jan: "4580828678323",
    image_url: "/figures/nendoroid-shinsuke-takasugi-gintama/thumb.jpg",
    images: [
      "/figures/nendoroid-shinsuke-takasugi-gintama/01.jpg",
      "/figures/nendoroid-shinsuke-takasugi-gintama/02.jpg",
      "/figures/nendoroid-shinsuke-takasugi-gintama/03.jpg",
      "/figures/nendoroid-shinsuke-takasugi-gintama/04.jpg",
      "/figures/nendoroid-shinsuke-takasugi-gintama/05.jpg",
    ],
  },
  {
    id: "22",
    droppedAt: "2026-06-21",
    name: "Plafia Doala (Visitor Ver.) Plastic Model [PLUMPMOA]",
    series: "Doala",
    manufacturer: "PLUM",
    type: "Model Kit",
    price_jpy: 3828,
    price_usd: 26,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-08-31",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    quantity: 200,
    availability: "available",
    jan: "4580843590037",
    image_url: "/figures/plafia-doala-visitor-ver/thumb.jpg",
    images: [
      "/figures/plafia-doala-visitor-ver/01.jpg",
      "/figures/plafia-doala-visitor-ver/02.jpg",
      "/figures/plafia-doala-visitor-ver/03.jpg",
      "/figures/plafia-doala-visitor-ver/04.jpg",
      "/figures/plafia-doala-visitor-ver/05.jpg",
      "/figures/plafia-doala-visitor-ver/06.jpg",
      "/figures/plafia-doala-visitor-ver/07.jpg",
      "/figures/plafia-doala-visitor-ver/08.jpg",
    ],
  },
  {
    id: "23",
    droppedAt: "2026-06-21",
    name: "B-Style Mirajane Strauss: Bunny Ver. FAIRY TAIL 1/4 Scale Figure",
    series: "Fairy Tail",
    manufacturer: "FREEing",
    type: "Scale",
    price_jpy: 36575,
    price_usd: 249,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2026-12-31",
    scale: "1/4",
    height: "47cm",
    featured: false,
    quantity: 198,
    availability: "available",
    jan: "4570001515125",
    image_url: "/figures/b-style-mirajane-strauss/thumb.jpg",
    images: [
      "/figures/b-style-mirajane-strauss/01.jpg",
      "/figures/b-style-mirajane-strauss/02.jpg",
      "/figures/b-style-mirajane-strauss/03.jpg",
      "/figures/b-style-mirajane-strauss/04.jpg",
      "/figures/b-style-mirajane-strauss/05.jpg",
      "/figures/b-style-mirajane-strauss/06.jpg",
      "/figures/b-style-mirajane-strauss/07.jpg",
      "/figures/b-style-mirajane-strauss/08.jpg",
    ],
  },
  {
    id: "24",
    droppedAt: "2026-06-21",
    name: "Hatsune Miku: Music & Fire Works Ver. - Character Vocal Series 01: Hatsune 1/7 Scale Figure",
    series: "Vocaloid",
    manufacturer: "Good Smile Company",
    type: "Scale",
    price_jpy: 26410,
    price_usd: 180,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-06-30",
    scale: "1/7",
    height: "32cm",
    featured: false,
    quantity: 196,
    availability: "available",
    jan: "4570232587038",
    image_url: "/figures/hatsune-miku-music-fire/thumb.jpg",
    images: [
      "/figures/hatsune-miku-music-fire/01.jpg",
      "/figures/hatsune-miku-music-fire/02.jpg",
      "/figures/hatsune-miku-music-fire/03.jpg",
      "/figures/hatsune-miku-music-fire/04.jpg",
      "/figures/hatsune-miku-music-fire/05.jpg",
      "/figures/hatsune-miku-music-fire/06.jpg",
      "/figures/hatsune-miku-music-fire/07.jpg",
      "/figures/hatsune-miku-music-fire/08.jpg",
    ],
  },
  {
    id: "25",
    droppedAt: "2026-06-21",
    name: "Nendoroid Mahiru Shiina The Angel Next Door Spoils Me Rotten Figure Reissue",
    series: "The Angel Next Door",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 5848,
    price_usd: 40,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    release_date: "2027-01-31",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    quantity: 199,
    availability: "available",
    jan: "4570232585256",
    image_url: "/figures/nendoroid-mahiru-shiina-the/thumb.jpg",
    images: [
      "/figures/nendoroid-mahiru-shiina-the/01.jpg",
      "/figures/nendoroid-mahiru-shiina-the/02.jpg",
      "/figures/nendoroid-mahiru-shiina-the/03.jpg",
      "/figures/nendoroid-mahiru-shiina-the/04.jpg",
      "/figures/nendoroid-mahiru-shiina-the/05.jpg",
    ],
  },
  {
    id: "26",
    droppedAt: "2026-06-22",
    name: "Capcom Figure Builder Soft Vinyl Monster Hunter - Gore Magala",
    jan: "4976219139328",
    series: "Monster Hunter",
    manufacturer: "Capcom",
    type: "Figure",
    price_jpy: 5065,
    price_usd: 34,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 196,
    availability: "available",
    release_date: "2027-02-28",
    scale: "—",
    height: "21cm",
    featured: false,
    image_url: "/figures/capcom-figure-builder-soft/02.jpg",
    images: [
      "/figures/capcom-figure-builder-soft/01.jpg",
      "/figures/capcom-figure-builder-soft/02.jpg",
      "/figures/capcom-figure-builder-soft/03.jpg",
      "/figures/capcom-figure-builder-soft/04.jpg",
      "/figures/capcom-figure-builder-soft/05.jpg",
      "/figures/capcom-figure-builder-soft/06.jpg",
    ],
  },
  {
    id: "27",
    droppedAt: "2026-06-22",
    name: "Movie Masterpiece - Alien Warrior (2.0) : Aliens 1/6 Scale Fully Poseable Figure Deluxe Version",
    jan: "4570192000325",
    series: "Aliens",
    manufacturer: "Hot Toys",
    type: "Scale",
    price_jpy: 49680,
    price_usd: 338,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 199,
    availability: "available",
    release_date: "2027-09-30",
    scale: "1/6",
    height: "39cm",
    featured: false,
    image_url: "/figures/movie-masterpiece-alien-warrior/thumb.jpg",
    images: [
      "/figures/movie-masterpiece-alien-warrior/01.jpg",
      "/figures/movie-masterpiece-alien-warrior/02.jpg",
      "/figures/movie-masterpiece-alien-warrior/03.jpg",
      "/figures/movie-masterpiece-alien-warrior/04.jpg",
      "/figures/movie-masterpiece-alien-warrior/05.jpg",
      "/figures/movie-masterpiece-alien-warrior/06.jpg",
      "/figures/movie-masterpiece-alien-warrior/07.jpg",
      "/figures/movie-masterpiece-alien-warrior/08.jpg",
    ],
  },
  {
    id: "28",
    droppedAt: "2026-06-22",
    name: "Movie Masterpiece - Alien Warrior (2.0) : Aliens 1/6 Scale Fully Poseable Figure",
    jan: "4570192000318",
    series: "Aliens",
    manufacturer: "Hot Toys",
    type: "Scale",
    price_jpy: 46000,
    price_usd: 313,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2027-09-30",
    scale: "1/6",
    height: "39cm",
    featured: false,
    image_url: "/figures/movie-masterpiece-alien-warrior-x/thumb.jpg",
    images: [
      "/figures/movie-masterpiece-alien-warrior-x/01.jpg",
      "/figures/movie-masterpiece-alien-warrior-x/02.jpg",
      "/figures/movie-masterpiece-alien-warrior-x/03.jpg",
      "/figures/movie-masterpiece-alien-warrior-x/04.jpg",
      "/figures/movie-masterpiece-alien-warrior-x/05.jpg",
      "/figures/movie-masterpiece-alien-warrior-x/06.jpg",
      "/figures/movie-masterpiece-alien-warrior-x/07.jpg",
      "/figures/movie-masterpiece-alien-warrior-x/08.jpg",
    ],
  },
  {
    id: "29",
    droppedAt: "2026-06-22",
    name: "Movie Masterpiece - Ellen Ripley (2.0) : Aliens 1/6 Scale Fully Poseable Figure Deluxe Version",
    jan: "4570192000301",
    series: "Aliens",
    manufacturer: "Hot Toys",
    type: "Scale",
    price_jpy: 47840,
    price_usd: 325,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2027-09-30",
    scale: "1/6",
    height: "30cm",
    featured: false,
    image_url: "/figures/movie-masterpiece-ellen-ripley/thumb.jpg",
    images: [
      "/figures/movie-masterpiece-ellen-ripley/01.jpg",
      "/figures/movie-masterpiece-ellen-ripley/02.jpg",
      "/figures/movie-masterpiece-ellen-ripley/03.jpg",
      "/figures/movie-masterpiece-ellen-ripley/04.jpg",
      "/figures/movie-masterpiece-ellen-ripley/05.jpg",
      "/figures/movie-masterpiece-ellen-ripley/06.jpg",
      "/figures/movie-masterpiece-ellen-ripley/07.jpg",
      "/figures/movie-masterpiece-ellen-ripley/08.jpg",
    ],
  },
  {
    id: "30",
    droppedAt: "2026-06-22",
    name: "Portrait.Of.Pirates \"S.O.C\" Sanji Ver.R One Piece Figure Limited Edition",
    jan: "",
    series: "One Piece",
    manufacturer: "Bandai MegaHouse",
    type: "Scale",
    price_jpy: 21790,
    price_usd: 148,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 18,
    availability: "available",
    release_date: "2026-11-30",
    scale: "1/8",
    height: "14cm",
    featured: false,
    image_url: "/figures/portraitofpirates-soc-sanji-verr/01.jpg",
    images: [
      "/figures/portraitofpirates-soc-sanji-verr/01.jpg",
      "/figures/portraitofpirates-soc-sanji-verr/02.jpg",
      "/figures/portraitofpirates-soc-sanji-verr/03.jpg",
      "/figures/portraitofpirates-soc-sanji-verr/04.jpg",
      "/figures/portraitofpirates-soc-sanji-verr/05.jpg",
      "/figures/portraitofpirates-soc-sanji-verr/06.jpg",
      "/figures/portraitofpirates-soc-sanji-verr/07.jpg",
      "/figures/portraitofpirates-soc-sanji-verr/08.jpg",
    ],
  },
  {
    id: "31",
    droppedAt: "2026-06-22",
    name: "Large Monster Series ULTRA NEW GENERATION Ultraman Z Original Complete Figure [PLEX]",
    jan: "4532149025751",
    series: "Ultraman",
    manufacturer: "Plex",
    type: "Figure",
    price_jpy: 20493,
    price_usd: 139,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2026-09-30",
    scale: "—",
    height: "25cm",
    featured: false,
    image_url: "/figures/large-monster-series-ultra/01.jpg",
    images: [
      "/figures/large-monster-series-ultra/01.jpg",
      "/figures/large-monster-series-ultra/02.jpg",
      "/figures/large-monster-series-ultra/03.jpg",
      "/figures/large-monster-series-ultra/04.jpg",
      "/figures/large-monster-series-ultra/05.jpg",
      "/figures/large-monster-series-ultra/06.jpg",
      "/figures/large-monster-series-ultra/07.jpg",
    ],
  },
  {
    id: "32",
    droppedAt: "2026-06-22",
    name: "DLX Spider-Man Symbiote Suit (Peter Parker) Standard Edition - Marvel's Spider-Man 2 1/12 Action Figure",
    jan: "4595430617264",
    series: "Marvel's Spider-Man 2",
    manufacturer: "threezero",
    type: "Scale",
    price_jpy: 13811,
    price_usd: 94,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 196,
    availability: "available",
    release_date: "2026-12-31",
    scale: "1/12",
    height: "15cm",
    featured: false,
    image_url: "/figures/dlx-spider-man-symbiote/thumb.jpg",
    images: [
      "/figures/dlx-spider-man-symbiote/01.jpg",
      "/figures/dlx-spider-man-symbiote/02.jpg",
      "/figures/dlx-spider-man-symbiote/03.jpg",
      "/figures/dlx-spider-man-symbiote/04.jpg",
      "/figures/dlx-spider-man-symbiote/05.jpg",
      "/figures/dlx-spider-man-symbiote/06.jpg",
      "/figures/dlx-spider-man-symbiote/07.jpg",
      "/figures/dlx-spider-man-symbiote/08.jpg",
    ],
  },
  {
    id: "33",
    droppedAt: "2026-06-22",
    name: "Pokémon Scale World Sinnoh Region Palkia",
    jan: "4570117928963",
    series: "Pokémon",
    manufacturer: "Bandai",
    type: "Scale",
    price_jpy: 15890,
    price_usd: 108,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 8,
    availability: "last_remaining_items",
    release_date: "2026-10-31",
    scale: "1/20",
    height: "23cm",
    featured: false,
    image_url: "/figures/pokemon-scale-world-sinnoh-palkia/01.jpg",
    images: [
      "/figures/pokemon-scale-world-sinnoh-palkia/01.jpg",
      "/figures/pokemon-scale-world-sinnoh-palkia/02.jpg",
      "/figures/pokemon-scale-world-sinnoh-palkia/03.jpg",
      "/figures/pokemon-scale-world-sinnoh-palkia/04.jpg",
    ],
  },
  {
    id: "34",
    droppedAt: "2026-06-22",
    name: "Pokémon Scale World Sinnoh Region Dialga",
    jan: "4570117928956",
    series: "Pokémon",
    manufacturer: "Bandai",
    type: "Scale",
    price_jpy: 15890,
    price_usd: 108,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 8,
    availability: "last_remaining_items",
    release_date: "2026-10-31",
    scale: "1/20",
    height: "27cm",
    featured: false,
    image_url: "/figures/pokemon-scale-world-sinnoh-x/thumb.jpg",
    images: [
      "/figures/pokemon-scale-world-sinnoh-x/01.jpg",
      "/figures/pokemon-scale-world-sinnoh-x/02.jpg",
      "/figures/pokemon-scale-world-sinnoh-x/03.jpg",
      "/figures/pokemon-scale-world-sinnoh-x/04.jpg",
    ],
  },
  {
    id: "35",
    droppedAt: "2026-06-22",
    name: "Daiblos Core Maree Rouge Rakubai no Utage Wet ver. 1/6 Scale Figure [KAWA DESIGN]",
    jan: "6979060800179",
    series: "Daiblos Core",
    manufacturer: "KAWA DESIGN",
    type: "Scale",
    price_jpy: 18216,
    price_usd: 124,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 197,
    availability: "available",
    release_date: "2027-05-31",
    scale: "1/6",
    height: "25cm",
    featured: false,
    image_url: "/figures/daiblos-core-maree-rouge/thumb.jpg",
    images: [
      "/figures/daiblos-core-maree-rouge/01.jpg",
      "/figures/daiblos-core-maree-rouge/02.jpg",
      "/figures/daiblos-core-maree-rouge/03.jpg",
      "/figures/daiblos-core-maree-rouge/04.jpg",
      "/figures/daiblos-core-maree-rouge/05.jpg",
      "/figures/daiblos-core-maree-rouge/06.jpg",
      "/figures/daiblos-core-maree-rouge/07.jpg",
      "/figures/daiblos-core-maree-rouge/08.jpg",
    ],
  },
  {
    id: "36",
    droppedAt: "2026-06-22",
    name: "Daiblos Core Maree Rouge Rakubai no Utage 1/6 Scale Figure [KAWA DESIGN]",
    jan: "6979060800162",
    series: "Daiblos Core",
    manufacturer: "KAWA DESIGN",
    type: "Scale",
    price_jpy: 18216,
    price_usd: 124,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2027-05-31",
    scale: "1/6",
    height: "25cm",
    featured: false,
    image_url: "/figures/daiblos-core-maree-rouge-x/thumb.jpg",
    images: [
      "/figures/daiblos-core-maree-rouge-x/01.jpg",
      "/figures/daiblos-core-maree-rouge-x/02.jpg",
      "/figures/daiblos-core-maree-rouge-x/03.jpg",
      "/figures/daiblos-core-maree-rouge-x/04.jpg",
      "/figures/daiblos-core-maree-rouge-x/05.jpg",
      "/figures/daiblos-core-maree-rouge-x/06.jpg",
      "/figures/daiblos-core-maree-rouge-x/07.jpg",
      "/figures/daiblos-core-maree-rouge-x/08.jpg",
    ],
  },
  {
    id: "37",
    droppedAt: "2026-06-22",
    name: "Miko Shoujo MIKO Race Queen Ver. 1/7 Scale Figure Deluxe Edition [Hobby Sakura]",
    jan: "6979272330723",
    series: "Miko Shoujo",
    manufacturer: "Hobby Sakura",
    type: "Scale",
    price_jpy: 23529,
    price_usd: 160,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 198,
    availability: "available",
    release_date: "2027-02-28",
    scale: "1/7",
    height: "33cm",
    featured: false,
    image_url: "/figures/miko-shoujo-miko-race/thumb.jpg",
    images: [
      "/figures/miko-shoujo-miko-race/01.jpg",
      "/figures/miko-shoujo-miko-race/02.jpg",
      "/figures/miko-shoujo-miko-race/03.jpg",
      "/figures/miko-shoujo-miko-race/04.jpg",
      "/figures/miko-shoujo-miko-race/05.jpg",
      "/figures/miko-shoujo-miko-race/06.jpg",
      "/figures/miko-shoujo-miko-race/07.jpg",
      "/figures/miko-shoujo-miko-race/08.jpg",
    ],
  },
  {
    id: "38",
    droppedAt: "2026-06-22",
    name: "Miko Shoujo MIKO Race Queen Ver. 1/7 Scale Figure [Hobby Sakura]",
    jan: "6979272330716",
    series: "Miko Shoujo",
    manufacturer: "Hobby Sakura",
    type: "Scale",
    price_jpy: 21483,
    price_usd: 146,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 198,
    availability: "available",
    release_date: "2027-02-28",
    scale: "1/7",
    height: "33cm",
    featured: false,
    image_url: "/figures/miko-shoujo-miko-race-x/thumb.jpg",
    images: [
      "/figures/miko-shoujo-miko-race-x/01.jpg",
      "/figures/miko-shoujo-miko-race-x/02.jpg",
      "/figures/miko-shoujo-miko-race-x/03.jpg",
      "/figures/miko-shoujo-miko-race-x/04.jpg",
      "/figures/miko-shoujo-miko-race-x/05.jpg",
      "/figures/miko-shoujo-miko-race-x/06.jpg",
      "/figures/miko-shoujo-miko-race-x/07.jpg",
      "/figures/miko-shoujo-miko-race-x/08.jpg",
    ],
  },
  {
    id: "39",
    droppedAt: "2026-06-22",
    name: "Megami Device B1R-L Chassis Kit Skin Color E 1/1 Plastic Model",
    jan: "4934054082537",
    series: "Megami Device",
    manufacturer: "Kotobukiya",
    type: "Model Kit",
    price_jpy: 4574,
    price_usd: 31,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 12,
    availability: "available",
    release_date: "2026-10-31",
    scale: "1/1",
    height: "0cm",
    featured: false,
    image_url: "/figures/megami-device-b1r-l/thumb.jpg",
    images: [
      "/figures/megami-device-b1r-l/01.jpg",
      "/figures/megami-device-b1r-l/02.jpg",
      "/figures/megami-device-b1r-l/03.jpg",
      "/figures/megami-device-b1r-l/04.jpg",
      "/figures/megami-device-b1r-l/05.jpg",
      "/figures/megami-device-b1r-l/06.jpg",
      "/figures/megami-device-b1r-l/07.jpg",
      "/figures/megami-device-b1r-l/08.jpg",
    ],
  },
  {
    id: "40",
    droppedAt: "2026-06-22",
    name: "DIGACTION \"Fist of the North Star\" Shin & Heart Set Figure Reissue",
    jan: "4595985300345",
    series: "Fist of the North Star",
    manufacturer: "—",
    type: "Scale",
    price_jpy: 8217,
    price_usd: 56,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2026-09-30",
    scale: "1/24",
    height: "8cm",
    featured: false,
    image_url: "/figures/digaction-fist-of-the/thumb.jpg",
    images: [
      "/figures/digaction-fist-of-the/01.jpg",
      "/figures/digaction-fist-of-the/02.jpg",
      "/figures/digaction-fist-of-the/03.jpg",
      "/figures/digaction-fist-of-the/04.jpg",
      "/figures/digaction-fist-of-the/05.jpg",
      "/figures/digaction-fist-of-the/06.jpg",
      "/figures/digaction-fist-of-the/07.jpg",
      "/figures/digaction-fist-of-the/08.jpg",
    ],
  },
  {
    id: "41",
    droppedAt: "2026-06-22",
    name: "Scream Greats Series - Butterball Cenobite Hellraiser 8-Inch Action Figure",
    jan: "4570192000240",
    series: "Hellraiser",
    manufacturer: "Trick or Treat Studios",
    type: "Figure",
    price_jpy: 5904,
    price_usd: 40,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2026-12-31",
    scale: "—",
    height: "20cm",
    featured: false,
    image_url: "/figures/scream-greats-series-butterball/thumb.jpg",
    images: [
      "/figures/scream-greats-series-butterball/01.jpg",
      "/figures/scream-greats-series-butterball/02.jpg",
      "/figures/scream-greats-series-butterball/03.jpg",
      "/figures/scream-greats-series-butterball/04.jpg",
      "/figures/scream-greats-series-butterball/05.jpg",
      "/figures/scream-greats-series-butterball/06.jpg",
    ],
  },
  {
    id: "42",
    droppedAt: "2026-06-22",
    name: "Scream Greats Series - Chatterer Cenobite Hellraiser 8-Inch Action Figure",
    jan: "4570192000226",
    series: "Hellraiser",
    manufacturer: "Trick or Treat Studios",
    type: "Figure",
    price_jpy: 5904,
    price_usd: 40,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 199,
    availability: "available",
    release_date: "2026-12-31",
    scale: "—",
    height: "20cm",
    featured: false,
    image_url: "/figures/scream-greats-series-chatterer/thumb.jpg",
    images: [
      "/figures/scream-greats-series-chatterer/01.jpg",
      "/figures/scream-greats-series-chatterer/02.jpg",
      "/figures/scream-greats-series-chatterer/03.jpg",
      "/figures/scream-greats-series-chatterer/04.jpg",
      "/figures/scream-greats-series-chatterer/05.jpg",
      "/figures/scream-greats-series-chatterer/06.jpg",
    ],
  },
  {
    id: "43",
    droppedAt: "2026-06-22",
    name: "Scream Greats Series - Female Cenobite Hellraiser 8-Inch Action Figure",
    jan: "4570192000233",
    series: "Hellraiser",
    manufacturer: "Trick or Treat Studios",
    type: "Figure",
    price_jpy: 5904,
    price_usd: 40,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2026-12-31",
    scale: "—",
    height: "20cm",
    featured: false,
    image_url: "/figures/scream-greats-series-female/thumb.jpg",
    images: [
      "/figures/scream-greats-series-female/01.jpg",
      "/figures/scream-greats-series-female/02.jpg",
      "/figures/scream-greats-series-female/03.jpg",
      "/figures/scream-greats-series-female/04.jpg",
      "/figures/scream-greats-series-female/05.jpg",
      "/figures/scream-greats-series-female/06.jpg",
    ],
  },
  {
    id: "44",
    droppedAt: "2026-06-22",
    name: "Scream Greats Series - Pinhead Hellraiser 8-Inch Action Figure",
    jan: "4570192000219",
    series: "Hellraiser",
    manufacturer: "Trick or Treat Studios",
    type: "Figure",
    price_jpy: 5904,
    price_usd: 40,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 199,
    availability: "available",
    release_date: "2026-12-31",
    scale: "—",
    height: "20cm",
    featured: false,
    image_url: "/figures/scream-greats-series-pinhead/thumb.jpg",
    images: [
      "/figures/scream-greats-series-pinhead/01.jpg",
      "/figures/scream-greats-series-pinhead/02.jpg",
      "/figures/scream-greats-series-pinhead/03.jpg",
      "/figures/scream-greats-series-pinhead/04.jpg",
      "/figures/scream-greats-series-pinhead/05.jpg",
      "/figures/scream-greats-series-pinhead/06.jpg",
    ],
  },
  {
    id: "45",
    droppedAt: "2026-06-22",
    name: "HY-051 Demon Horse Nightmare 1/12 Scale Action Figure [Fish Toys]",
    jan: "6977674380117",
    series: "—",
    manufacturer: "Fish Toys",
    type: "Scale",
    price_jpy: 26919,
    price_usd: 183,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2026-12-31",
    scale: "1/12",
    height: "—",
    featured: false,
    image_url: "/figures/hy-051-demon-horse/thumb.jpg",
    images: [
      "/figures/hy-051-demon-horse/01.jpg",
      "/figures/hy-051-demon-horse/02.jpg",
      "/figures/hy-051-demon-horse/03.jpg",
      "/figures/hy-051-demon-horse/04.jpg",
      "/figures/hy-051-demon-horse/05.jpg",
      "/figures/hy-051-demon-horse/06.jpg",
      "/figures/hy-051-demon-horse/07.jpg",
      "/figures/hy-051-demon-horse/08.jpg",
    ],
  },
  {
    id: "46",
    droppedAt: "2026-06-22",
    name: "Mega Man X Action Figure Sigma [Hiya Toys]",
    jan: "6957534205170",
    series: "Mega Man",
    manufacturer: "Hiya Toys",
    type: "Scale",
    price_jpy: 17391,
    price_usd: 118,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 193,
    availability: "available",
    release_date: "2027-09-30",
    scale: "1/12",
    height: "18cm",
    featured: false,
    image_url: "/figures/mega-man-x-action/01.jpg",
    images: [
      "/figures/mega-man-x-action/01.jpg",
      "/figures/mega-man-x-action/02.jpg",
      "/figures/mega-man-x-action/03.jpg",
      "/figures/mega-man-x-action/04.jpg",
      "/figures/mega-man-x-action/05.jpg",
      "/figures/mega-man-x-action/06.jpg",
      "/figures/mega-man-x-action/07.jpg",
      "/figures/mega-man-x-action/08.jpg",
    ],
  },
  {
    id: "47",
    droppedAt: "2026-06-22",
    name: "Lilja Katsuragi-Hakusen- THE IDOLM@STER Gakuen 1/7 Scale Figure",
    jan: "4934054077878",
    series: "Gakuen iDOLM@STER",
    manufacturer: "Kotobukiya",
    type: "Scale",
    price_jpy: 20812,
    price_usd: 142,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2026-12-31",
    scale: "1/7",
    height: "23cm",
    featured: false,
    image_url: "/figures/lilja-katsuragi-hakusen-the/thumb.jpg",
    images: [
      "/figures/lilja-katsuragi-hakusen-the/01.jpg",
      "/figures/lilja-katsuragi-hakusen-the/02.jpg",
      "/figures/lilja-katsuragi-hakusen-the/03.jpg",
      "/figures/lilja-katsuragi-hakusen-the/04.jpg",
      "/figures/lilja-katsuragi-hakusen-the/05.jpg",
      "/figures/lilja-katsuragi-hakusen-the/06.jpg",
      "/figures/lilja-katsuragi-hakusen-the/07.jpg",
      "/figures/lilja-katsuragi-hakusen-the/08.jpg",
    ],
  },
  {
    id: "48",
    droppedAt: "2026-06-22",
    name: "Nendoroid Doll Phainon: Express Travel Ver. Honkai: Star Rail Figure Limited Bonus Set",
    jan: "4570232586970",
    series: "Honkai: Star Rail",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 10880,
    price_usd: 74,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 56,
    availability: "available",
    release_date: "2027-02-28",
    scale: "—",
    height: "15cm",
    featured: false,
    image_url: "/figures/nendoroid-doll-phainon-express/thumb.jpg",
    images: [
      "/figures/nendoroid-doll-phainon-express/01.jpg",
      "/figures/nendoroid-doll-phainon-express/02.jpg",
      "/figures/nendoroid-doll-phainon-express/03.jpg",
      "/figures/nendoroid-doll-phainon-express/04.jpg",
      "/figures/nendoroid-doll-phainon-express/05.jpg",
      "/figures/nendoroid-doll-phainon-express/06.jpg",
      "/figures/nendoroid-doll-phainon-express/07.jpg",
      "/figures/nendoroid-doll-phainon-express/08.jpg",
    ],
  },
  {
    id: "49",
    droppedAt: "2026-06-22",
    name: "MODEROID Testa-Rossa, the Vermillion Knight - The Legend of Heroes: Trails of Cold Steel Plastic Model",
    jan: "4570232586963",
    series: "The Legend of Heroes: Trails of Cold Steel",
    manufacturer: "Good Smile Company",
    type: "Model Kit",
    price_jpy: 4455,
    price_usd: 30,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 190,
    availability: "available",
    release_date: "2026-12-31",
    scale: "Non-scale",
    height: "18cm",
    featured: false,
    image_url: "/figures/moderoid-testa-rossa-the/thumb.jpg",
    images: [
      "/figures/moderoid-testa-rossa-the/01.jpg",
      "/figures/moderoid-testa-rossa-the/02.jpg",
      "/figures/moderoid-testa-rossa-the/03.jpg",
      "/figures/moderoid-testa-rossa-the/04.jpg",
      "/figures/moderoid-testa-rossa-the/05.jpg",
      "/figures/moderoid-testa-rossa-the/06.jpg",
      "/figures/moderoid-testa-rossa-the/07.jpg",
      "/figures/moderoid-testa-rossa-the/08.jpg",
    ],
  },
  {
    id: "50",
    droppedAt: "2026-06-22",
    name: "Nendoroid Anaxa - Honkai: Star Rail Figure",
    jan: "4570232583597",
    series: "Honkai: Star Rail",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 6794,
    price_usd: 46,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 191,
    availability: "available",
    release_date: "2026-12-31",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    image_url: "/figures/nendoroid-anaxa-honkai-star/thumb.jpg",
    images: [
      "/figures/nendoroid-anaxa-honkai-star/01.jpg",
      "/figures/nendoroid-anaxa-honkai-star/02.jpg",
      "/figures/nendoroid-anaxa-honkai-star/03.jpg",
      "/figures/nendoroid-anaxa-honkai-star/04.jpg",
      "/figures/nendoroid-anaxa-honkai-star/05.jpg",
      "/figures/nendoroid-anaxa-honkai-star/06.jpg",
      "/figures/nendoroid-anaxa-honkai-star/07.jpg",
      "/figures/nendoroid-anaxa-honkai-star/08.jpg",
    ],
  },
  {
    id: "51",
    droppedAt: "2026-06-22",
    name: "PLAMATEA Black Honey - Cutie Honey Nova Plastic Model",
    jan: "4570232582033",
    series: "Cutie Honey Nova",
    manufacturer: "Good Smile Company",
    type: "Model Kit",
    price_jpy: 7128,
    price_usd: 48,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 194,
    availability: "available",
    release_date: "2026-12-31",
    scale: "Non-scale",
    height: "17cm",
    featured: false,
    image_url: "/figures/plamatea-black-honey-cutie/thumb.jpg",
    images: [
      "/figures/plamatea-black-honey-cutie/01.jpg",
      "/figures/plamatea-black-honey-cutie/02.jpg",
      "/figures/plamatea-black-honey-cutie/03.jpg",
      "/figures/plamatea-black-honey-cutie/04.jpg",
      "/figures/plamatea-black-honey-cutie/05.jpg",
      "/figures/plamatea-black-honey-cutie/06.jpg",
      "/figures/plamatea-black-honey-cutie/07.jpg",
      "/figures/plamatea-black-honey-cutie/08.jpg",
    ],
  },
  {
    id: "52",
    droppedAt: "2026-06-22",
    name: "AMK Pro Series: Evangelion Unit-01 : Rebuild of Evangelion Plastic Model",
    jan: "4975406510438",
    series: "Rebuild of Evangelion",
    manufacturer: "AMK",
    type: "Model Kit",
    price_jpy: 16236,
    price_usd: 110,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2026-07-31",
    scale: "—",
    height: "20cm",
    featured: false,
    image_url: "/figures/amk-pro-series-evangelion/thumb.jpg",
    images: [
      "/figures/amk-pro-series-evangelion/01.jpg",
      "/figures/amk-pro-series-evangelion/02.jpg",
      "/figures/amk-pro-series-evangelion/03.jpg",
      "/figures/amk-pro-series-evangelion/04.jpg",
      "/figures/amk-pro-series-evangelion/05.jpg",
      "/figures/amk-pro-series-evangelion/06.jpg",
      "/figures/amk-pro-series-evangelion/07.jpg",
      "/figures/amk-pro-series-evangelion/08.jpg",
    ],
  },
  {
    id: "53",
    droppedAt: "2026-06-22",
    name: "Girls' Frontline Desert Eagle 1/7 Scale Figure [ques Q]",
    jan: "4560393843265",
    series: "Girls' Frontline",
    manufacturer: "Ques Q",
    type: "Scale",
    price_jpy: 25381,
    price_usd: 173,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2027-05-31",
    scale: "1/7",
    height: "22.5cm",
    featured: false,
    image_url: "/figures/girls-frontline-desert-eagle/thumb.jpg",
    images: [
      "/figures/girls-frontline-desert-eagle/01.jpg",
      "/figures/girls-frontline-desert-eagle/02.jpg",
      "/figures/girls-frontline-desert-eagle/03.jpg",
      "/figures/girls-frontline-desert-eagle/04.jpg",
      "/figures/girls-frontline-desert-eagle/05.jpg",
      "/figures/girls-frontline-desert-eagle/06.jpg",
      "/figures/girls-frontline-desert-eagle/07.jpg",
      "/figures/girls-frontline-desert-eagle/08.jpg",
    ],
  },
  {
    id: "54",
    droppedAt: "2026-06-22",
    name: "Nendoroid Guts Berserk Figure Reissue",
    jan: "4570232586161",
    series: "Berserk",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 6450,
    price_usd: 44,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 198,
    availability: "available",
    release_date: "2027-03-31",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    image_url: "/figures/nendoroid-guts-berserk-figure/thumb.jpg",
    images: [
      "/figures/nendoroid-guts-berserk-figure/01.jpg",
      "/figures/nendoroid-guts-berserk-figure/02.jpg",
      "/figures/nendoroid-guts-berserk-figure/03.jpg",
      "/figures/nendoroid-guts-berserk-figure/04.jpg",
      "/figures/nendoroid-guts-berserk-figure/05.jpg",
      "/figures/nendoroid-guts-berserk-figure/06.jpg",
    ],
  },
  {
    id: "55",
    droppedAt: "2026-06-22",
    name: "Nendoroid Asuka Shikinami Langley Rebuild of Evangelion Figure 2nd Reissue",
    jan: "4570232582149",
    series: "Rebuild of Evangelion",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 4558,
    price_usd: 31,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2027-02-28",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    image_url: "/figures/nendoroid-asuka-shikinami-langley/thumb.jpg",
    images: [
      "/figures/nendoroid-asuka-shikinami-langley/01.jpg",
      "/figures/nendoroid-asuka-shikinami-langley/02.jpg",
      "/figures/nendoroid-asuka-shikinami-langley/03.jpg",
      "/figures/nendoroid-asuka-shikinami-langley/04.jpg",
      "/figures/nendoroid-asuka-shikinami-langley/05.jpg",
      "/figures/nendoroid-asuka-shikinami-langley/06.jpg",
    ],
  },
  {
    id: "56",
    droppedAt: "2026-06-22",
    name: "Nendoroid Rei Ayanami Rebuild of Evangelion Figure 2nd Reissue",
    jan: "4570232582132",
    series: "Rebuild of Evangelion",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 4558,
    price_usd: 31,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2027-02-28",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    image_url: "/figures/nendoroid-rei-ayanami-rebuild/thumb.jpg",
    images: [
      "/figures/nendoroid-rei-ayanami-rebuild/01.jpg",
      "/figures/nendoroid-rei-ayanami-rebuild/02.jpg",
      "/figures/nendoroid-rei-ayanami-rebuild/03.jpg",
      "/figures/nendoroid-rei-ayanami-rebuild/04.jpg",
      "/figures/nendoroid-rei-ayanami-rebuild/05.jpg",
      "/figures/nendoroid-rei-ayanami-rebuild/06.jpg",
    ],
  },
  {
    id: "57",
    droppedAt: "2026-06-22",
    name: "Nendoroid Matikanetannhauser Umamusume Pretty Derby Figure Reissue",
    jan: "4570232586185",
    series: "Umamusume Pretty Derby",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 6708,
    price_usd: 46,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 190,
    availability: "available",
    release_date: "2026-11-30",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    image_url: "/figures/nendoroid-matikanetannhauser-umamusume-pretty/thumb.jpg",
    images: [
      "/figures/nendoroid-matikanetannhauser-umamusume-pretty/01.jpg",
      "/figures/nendoroid-matikanetannhauser-umamusume-pretty/02.jpg",
      "/figures/nendoroid-matikanetannhauser-umamusume-pretty/03.jpg",
      "/figures/nendoroid-matikanetannhauser-umamusume-pretty/04.jpg",
      "/figures/nendoroid-matikanetannhauser-umamusume-pretty/05.jpg",
      "/figures/nendoroid-matikanetannhauser-umamusume-pretty/06.jpg",
    ],
  },
  {
    id: "58",
    droppedAt: "2026-06-22",
    name: "OSHI WORKS Eren Yeager The Final Season ver. Attack on Titan Figure",
    jan: "4934054084364",
    series: "Attack on Titan",
    manufacturer: "Kotobukiya",
    type: "Figure",
    price_jpy: 7128,
    price_usd: 48,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 192,
    availability: "available",
    release_date: "2026-12-31",
    scale: "Non-scale",
    height: "23cm",
    featured: false,
    image_url: "/figures/oshi-works-eren-yeager/01.jpg",
    images: [
      "/figures/oshi-works-eren-yeager/01.jpg",
      "/figures/oshi-works-eren-yeager/02.jpg",
      "/figures/oshi-works-eren-yeager/03.jpg",
      "/figures/oshi-works-eren-yeager/04.jpg",
      "/figures/oshi-works-eren-yeager/05.jpg",
      "/figures/oshi-works-eren-yeager/06.jpg",
      "/figures/oshi-works-eren-yeager/07.jpg",
      "/figures/oshi-works-eren-yeager/08.jpg",
    ],
  },
  {
    id: "59",
    droppedAt: "2026-06-22",
    name: "OSHI WORKS Livio the Double Fang TRIGUN STAMPEDE Figure",
    jan: "4934054079841",
    series: "TRIGUN STAMPEDE",
    manufacturer: "Kotobukiya",
    type: "Scale",
    price_jpy: 7128,
    price_usd: 48,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 199,
    availability: "available",
    release_date: "2026-12-31",
    scale: "1/8",
    height: "22cm",
    featured: false,
    image_url: "/figures/oshi-works-livio-the/01.jpg",
    images: [
      "/figures/oshi-works-livio-the/01.jpg",
      "/figures/oshi-works-livio-the/02.jpg",
      "/figures/oshi-works-livio-the/03.jpg",
      "/figures/oshi-works-livio-the/04.jpg",
      "/figures/oshi-works-livio-the/05.jpg",
      "/figures/oshi-works-livio-the/06.jpg",
      "/figures/oshi-works-livio-the/07.jpg",
      "/figures/oshi-works-livio-the/08.jpg",
    ],
  },
  {
    id: "60",
    droppedAt: "2026-06-22",
    name: "Movie Maniacs: Don Corleone - Movie The Godfather 6 Inch Posed Statue [McFarlane Toys]",
    jan: "4570191994380",
    series: "The Godfather",
    manufacturer: "McFarlane Toys",
    type: "Figure",
    price_jpy: 4556,
    price_usd: 31,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2026-07-31",
    scale: "—",
    height: "15cm",
    featured: false,
    image_url: "/figures/movie-maniacs-don-corleone/01.jpg",
    images: [
      "/figures/movie-maniacs-don-corleone/01.jpg",
      "/figures/movie-maniacs-don-corleone/02.jpg",
      "/figures/movie-maniacs-don-corleone/03.jpg",
      "/figures/movie-maniacs-don-corleone/04.jpg",
      "/figures/movie-maniacs-don-corleone/05.jpg",
      "/figures/movie-maniacs-don-corleone/06.jpg",
      "/figures/movie-maniacs-don-corleone/07.jpg",
      "/figures/movie-maniacs-don-corleone/08.jpg",
    ],
  },
  {
    id: "61",
    droppedAt: "2026-06-22",
    name: "005 Captain America - Marvel Rivals - 1/10 Scale Posed Figure with Scene [McFarlane Toys]",
    jan: "4570191993406",
    series: "Marvel",
    manufacturer: "McFarlane Toys",
    type: "Scale",
    price_jpy: 4896,
    price_usd: 33,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2026-07-31",
    scale: "1/10",
    height: "18cm",
    featured: false,
    image_url: "/figures/005-captain-america-marvel/01.jpg",
    images: [
      "/figures/005-captain-america-marvel/01.jpg",
      "/figures/005-captain-america-marvel/02.jpg",
      "/figures/005-captain-america-marvel/03.jpg",
      "/figures/005-captain-america-marvel/04.jpg",
      "/figures/005-captain-america-marvel/05.jpg",
      "/figures/005-captain-america-marvel/06.jpg",
      "/figures/005-captain-america-marvel/07.jpg",
      "/figures/005-captain-america-marvel/08.jpg",
    ],
  },
  {
    id: "62",
    droppedAt: "2026-06-22",
    name: "003 Thor - Marvel Rivals - 1/10 Scale Posed Figure with Scene [McFarlane Toys]",
    jan: "4570191993383",
    series: "Marvel",
    manufacturer: "McFarlane Toys",
    type: "Scale",
    price_jpy: 4896,
    price_usd: 33,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2026-07-31",
    scale: "1/10",
    height: "18cm",
    featured: false,
    image_url: "/figures/003-thor-marvel-rivals/01.jpg",
    images: [
      "/figures/003-thor-marvel-rivals/01.jpg",
      "/figures/003-thor-marvel-rivals/02.jpg",
      "/figures/003-thor-marvel-rivals/03.jpg",
      "/figures/003-thor-marvel-rivals/04.jpg",
      "/figures/003-thor-marvel-rivals/05.jpg",
      "/figures/003-thor-marvel-rivals/06.jpg",
      "/figures/003-thor-marvel-rivals/07.jpg",
      "/figures/003-thor-marvel-rivals/08.jpg",
    ],
  },
  {
    id: "63",
    droppedAt: "2026-06-22",
    name: "002 Doctor Strange - Marvel Rivals - 1/10 Scale Posed Figure with Scene [McFarlane Toys]",
    jan: "4570191993376",
    series: "Marvel",
    manufacturer: "McFarlane Toys",
    type: "Scale",
    price_jpy: 4896,
    price_usd: 33,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2026-07-31",
    scale: "1/10",
    height: "18cm",
    featured: false,
    image_url: "/figures/002-doctor-strange-marvel/01.jpg",
    images: [
      "/figures/002-doctor-strange-marvel/01.jpg",
      "/figures/002-doctor-strange-marvel/02.jpg",
      "/figures/002-doctor-strange-marvel/03.jpg",
      "/figures/002-doctor-strange-marvel/04.jpg",
      "/figures/002-doctor-strange-marvel/05.jpg",
      "/figures/002-doctor-strange-marvel/06.jpg",
      "/figures/002-doctor-strange-marvel/07.jpg",
      "/figures/002-doctor-strange-marvel/08.jpg",
    ],
  },
  {
    id: "64",
    droppedAt: "2026-06-22",
    name: "Honkai: Star Rail Gift+ Cyrene Wonderful Holiday Ver. 1/8 Scale Figure [Myethos]",
    jan: "6942630830562",
    series: "Honkai: Star Rail",
    manufacturer: "Myethos",
    type: "Scale",
    price_jpy: 6433,
    price_usd: 44,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 188,
    availability: "available",
    release_date: "2027-01-31",
    scale: "1/8",
    height: "20cm",
    featured: false,
    image_url: "/figures/honkai-star-rail-gift/thumb.jpg",
    images: [
      "/figures/honkai-star-rail-gift/01.jpg",
      "/figures/honkai-star-rail-gift/02.jpg",
      "/figures/honkai-star-rail-gift/03.jpg",
      "/figures/honkai-star-rail-gift/04.jpg",
      "/figures/honkai-star-rail-gift/05.jpg",
      "/figures/honkai-star-rail-gift/06.jpg",
      "/figures/honkai-star-rail-gift/07.jpg",
      "/figures/honkai-star-rail-gift/08.jpg",
    ],
  },
  {
    id: "65",
    droppedAt: "2026-06-22",
    name: "HY-040 Flying Horse Wings of Light 1/12 Scale Action Figure [Fish Toy]",
    jan: "6977674380100",
    series: "—",
    manufacturer: "Fish Toys",
    type: "Scale",
    price_jpy: 16394,
    price_usd: 112,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 196,
    availability: "available",
    release_date: "2026-12-31",
    scale: "1/12",
    height: "68cm",
    featured: false,
    image_url: "/figures/hy-040-flying-horse/thumb.jpg",
    images: [
      "/figures/hy-040-flying-horse/01.jpg",
      "/figures/hy-040-flying-horse/02.jpg",
      "/figures/hy-040-flying-horse/03.jpg",
      "/figures/hy-040-flying-horse/04.jpg",
      "/figures/hy-040-flying-horse/05.jpg",
      "/figures/hy-040-flying-horse/06.jpg",
      "/figures/hy-040-flying-horse/07.jpg",
      "/figures/hy-040-flying-horse/08.jpg",
    ],
  },
  {
    id: "66",
    droppedAt: "2026-06-22",
    name: "The Man with No Name - The Good, The Bad, and The Ugly 1/6 Scale Fully Poseable Figure Reissue [Sideshow]",
    jan: "4570192000202",
    series: "The Good, the Bad and the Ugly",
    manufacturer: "Sideshow",
    type: "Scale",
    price_jpy: 50840,
    price_usd: 346,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 5,
    availability: "last_remaining_items",
    release_date: "2026-11-30",
    scale: "1/6",
    height: "31cm",
    featured: false,
    image_url: "/figures/the-man-with-no/thumb.jpg",
    images: [
      "/figures/the-man-with-no/01.jpg",
      "/figures/the-man-with-no/02.jpg",
      "/figures/the-man-with-no/03.jpg",
      "/figures/the-man-with-no/04.jpg",
      "/figures/the-man-with-no/05.jpg",
      "/figures/the-man-with-no/06.jpg",
      "/figures/the-man-with-no/07.jpg",
      "/figures/the-man-with-no/08.jpg",
    ],
  },
  {
    id: "67",
    droppedAt: "2026-06-22",
    name: "Doctor Doom Marvel Comics - Designers Statue by Tracy Tubera [Sideshow]",
    jan: "4570192000172",
    series: "Marvel",
    manufacturer: "Sideshow",
    type: "Figure",
    price_jpy: 32800,
    price_usd: 223,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2026-12-31",
    scale: "—",
    height: "25cm",
    featured: false,
    image_url: "/figures/doctor-doom-marvel-comics/thumb.jpg",
    images: [
      "/figures/doctor-doom-marvel-comics/01.jpg",
      "/figures/doctor-doom-marvel-comics/02.jpg",
      "/figures/doctor-doom-marvel-comics/03.jpg",
      "/figures/doctor-doom-marvel-comics/04.jpg",
      "/figures/doctor-doom-marvel-comics/05.jpg",
      "/figures/doctor-doom-marvel-comics/06.jpg",
      "/figures/doctor-doom-marvel-comics/07.jpg",
      "/figures/doctor-doom-marvel-comics/08.jpg",
    ],
  },
  {
    id: "68",
    droppedAt: "2026-06-22",
    name: "BIG Retro Sofvi Series: Godzilla (2001) Roaring Gravity Beam Absorption Image Ver. Figure [CCP Japan]",
    jan: "4580565647866",
    series: "Godzilla",
    manufacturer: "CCP Japan",
    type: "Figure",
    price_jpy: 16236,
    price_usd: 110,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 199,
    availability: "available",
    release_date: "2026-10-31",
    scale: "—",
    height: "25cm",
    featured: false,
    image_url: "/figures/big-retro-sofvi-series/thumb.jpg",
    images: [
      "/figures/big-retro-sofvi-series/01.jpg",
      "/figures/big-retro-sofvi-series/02.jpg",
      "/figures/big-retro-sofvi-series/03.jpg",
      "/figures/big-retro-sofvi-series/04.jpg",
      "/figures/big-retro-sofvi-series/05.jpg",
      "/figures/big-retro-sofvi-series/06.jpg",
      "/figures/big-retro-sofvi-series/07.jpg",
      "/figures/big-retro-sofvi-series/08.jpg",
    ],
  },
  {
    id: "69",
    droppedAt: "2026-06-22",
    name: "BIG Retro Sofvi Series: Godzilla (2001) Roaring Heat Ray Emission Ver. Figure [CCP Japan]",
    jan: "4580565647859",
    series: "Godzilla",
    manufacturer: "CCP Japan",
    type: "Figure",
    price_jpy: 16236,
    price_usd: 110,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 199,
    availability: "available",
    release_date: "2026-10-31",
    scale: "—",
    height: "25cm",
    featured: false,
    image_url: "/figures/big-retro-sofvi-series-x/thumb.jpg",
    images: [
      "/figures/big-retro-sofvi-series-x/01.jpg",
      "/figures/big-retro-sofvi-series-x/02.jpg",
      "/figures/big-retro-sofvi-series-x/03.jpg",
      "/figures/big-retro-sofvi-series-x/04.jpg",
      "/figures/big-retro-sofvi-series-x/05.jpg",
      "/figures/big-retro-sofvi-series-x/06.jpg",
      "/figures/big-retro-sofvi-series-x/07.jpg",
      "/figures/big-retro-sofvi-series-x/08.jpg",
    ],
  },
  {
    id: "70",
    droppedAt: "2026-06-22",
    name: "FFSC - Kittyfire : Mirrorman Completed Sofvi Figure [Future Quest]",
    jan: "4595432761057",
    series: "Mirrorman",
    manufacturer: "Future Quest",
    type: "Figure",
    price_jpy: 6970,
    price_usd: 47,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2026-10-31",
    scale: "—",
    height: "16cm",
    featured: false,
    image_url: "/figures/ffsc-kittyfire-mirrorman-completed/thumb.jpg",
    images: [
      "/figures/ffsc-kittyfire-mirrorman-completed/01.jpg",
      "/figures/ffsc-kittyfire-mirrorman-completed/02.jpg",
      "/figures/ffsc-kittyfire-mirrorman-completed/03.jpg",
    ],
  },
  {
    id: "71",
    droppedAt: "2026-06-22",
    name: "Aston Machan - Umamusume Pretty Derby 1/7 Scale Figure [Alter]",
    jan: "4560228207613",
    series: "Umamusume Pretty Derby",
    manufacturer: "Alter",
    type: "Scale",
    price_jpy: 24552,
    price_usd: 167,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 196,
    availability: "available",
    release_date: "2027-05-31",
    scale: "1/7",
    height: "26cm",
    featured: false,
    image_url: "/figures/aston-machan-umamusume-pretty/thumb.jpg",
    images: [
      "/figures/aston-machan-umamusume-pretty/01.jpg",
      "/figures/aston-machan-umamusume-pretty/02.jpg",
      "/figures/aston-machan-umamusume-pretty/03.jpg",
      "/figures/aston-machan-umamusume-pretty/04.jpg",
      "/figures/aston-machan-umamusume-pretty/05.jpg",
      "/figures/aston-machan-umamusume-pretty/06.jpg",
      "/figures/aston-machan-umamusume-pretty/07.jpg",
      "/figures/aston-machan-umamusume-pretty/08.jpg",
    ],
  },
  {
    id: "72",
    droppedAt: "2026-06-22",
    name: "Perlica - Arknights: Endfield 1/7 Scale Figure",
    jan: "4580828677906",
    series: "Arknights: Endfield",
    manufacturer: "Good Smile Arts Shanghai",
    type: "Scale",
    price_jpy: 25270,
    price_usd: 172,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 198,
    availability: "available",
    release_date: "2027-07-31",
    scale: "1/7",
    height: "32cm",
    featured: false,
    image_url: "/figures/perlica-arknights-endfield-17/thumb.jpg",
    images: [
      "/figures/perlica-arknights-endfield-17/01.jpg",
      "/figures/perlica-arknights-endfield-17/02.jpg",
      "/figures/perlica-arknights-endfield-17/03.jpg",
      "/figures/perlica-arknights-endfield-17/04.jpg",
      "/figures/perlica-arknights-endfield-17/05.jpg",
      "/figures/perlica-arknights-endfield-17/06.jpg",
      "/figures/perlica-arknights-endfield-17/07.jpg",
      "/figures/perlica-arknights-endfield-17/08.jpg",
    ],
  },
  {
    id: "73",
    droppedAt: "2026-06-22",
    name: "POP UP PARADE SP Cutie Honey - Cutie Honey Nova Figure",
    jan: "4570232586093",
    series: "Cutie Honey Nova",
    manufacturer: "Good Smile Company",
    type: "Pop Up Parade",
    price_jpy: 13608,
    price_usd: 93,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 192,
    availability: "available",
    release_date: "2026-11-30",
    scale: "1/6",
    height: "28cm",
    featured: false,
    image_url: "/figures/pop-up-parade-sp/thumb.jpg",
    images: [
      "/figures/pop-up-parade-sp/01.jpg",
      "/figures/pop-up-parade-sp/02.jpg",
      "/figures/pop-up-parade-sp/03.jpg",
      "/figures/pop-up-parade-sp/04.jpg",
      "/figures/pop-up-parade-sp/05.jpg",
      "/figures/pop-up-parade-sp/06.jpg",
      "/figures/pop-up-parade-sp/07.jpg",
      "/figures/pop-up-parade-sp/08.jpg",
    ],
  },
  {
    id: "74",
    droppedAt: "2026-06-22",
    name: "figma Klukai - Girls' Frontline 2: Exilium Limited Bonus Set",
    jan: "4545784070420",
    series: "Girls' Frontline 2: Exilium",
    manufacturer: "Max Factory",
    type: "Figma",
    price_jpy: 15190,
    price_usd: 103,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 49,
    availability: "available",
    release_date: "2027-04-30",
    scale: "—",
    height: "16cm",
    featured: false,
    image_url: "/figures/figma-klukai-girls-frontline/thumb.jpg",
    images: [
      "/figures/figma-klukai-girls-frontline/01.jpg",
      "/figures/figma-klukai-girls-frontline/02.jpg",
      "/figures/figma-klukai-girls-frontline/03.jpg",
      "/figures/figma-klukai-girls-frontline/04.jpg",
      "/figures/figma-klukai-girls-frontline/05.jpg",
      "/figures/figma-klukai-girls-frontline/06.jpg",
      "/figures/figma-klukai-girls-frontline/07.jpg",
      "/figures/figma-klukai-girls-frontline/08.jpg",
    ],
  },
  {
    id: "75",
    droppedAt: "2026-06-23",
    name: "Super Action Statue JoJo's Bizarre Adventure Part.3 The World Reissue",
    jan: "4570245827664",
    series: "JoJo's Bizarre Adventure",
    manufacturer: "Medicos Entertainment",
    type: "Figure",
    price_jpy: 8712,
    price_usd: 59,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 0,
    availability: "unavailable",
    release_date: "2027-01-31",
    scale: "—",
    height: "17cm",
    featured: false,
    image_url: "/figures/super-action-statue-jojo/thumb.jpg",
    images: [
      "/figures/super-action-statue-jojo/01.jpg",
      "/figures/super-action-statue-jojo/02.jpg",
      "/figures/super-action-statue-jojo/03.jpg",
      "/figures/super-action-statue-jojo/04.jpg",
      "/figures/super-action-statue-jojo/05.jpg",
    ],
  },
  {
    id: "76",
    droppedAt: "2026-06-23",
    name: "Super Action Statue JoJo's Bizarre Adventure Part.3 Dio Reissue",
    jan: "4570245827657",
    series: "JoJo's Bizarre Adventure",
    manufacturer: "Medicos Entertainment",
    type: "Figure",
    price_jpy: 8712,
    price_usd: 59,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 0,
    availability: "unavailable",
    release_date: "2027-01-31",
    scale: "—",
    height: "16cm",
    featured: false,
    image_url: "/figures/super-action-statue-jojo-x/thumb.jpg",
    images: [
      "/figures/super-action-statue-jojo-x/01.jpg",
      "/figures/super-action-statue-jojo-x/02.jpg",
      "/figures/super-action-statue-jojo-x/03.jpg",
      "/figures/super-action-statue-jojo-x/04.jpg",
    ],
  },
  {
    id: "77",
    droppedAt: "2026-06-23",
    name: "Rinami Himesaki: \"Semi-Blue With You Ver.\" - Gakuen Idolmaster 1/7 Scale Figure",
    jan: "4595122080215",
    series: "Gakuen iDOLM@STER",
    manufacturer: "Neonmax",
    type: "Scale",
    price_jpy: 21087,
    price_usd: 143,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2027-02-28",
    scale: "1/7",
    height: "—",
    featured: false,
    image_url: "/figures/rinami-himesaki-semi-blue/thumb.jpg",
    images: [
      "/figures/rinami-himesaki-semi-blue/01.jpg",
      "/figures/rinami-himesaki-semi-blue/02.jpg",
      "/figures/rinami-himesaki-semi-blue/03.jpg",
      "/figures/rinami-himesaki-semi-blue/04.jpg",
      "/figures/rinami-himesaki-semi-blue/05.jpg",
      "/figures/rinami-himesaki-semi-blue/06.jpg",
      "/figures/rinami-himesaki-semi-blue/07.jpg",
      "/figures/rinami-himesaki-semi-blue/08.jpg",
    ],
  },
  {
    id: "78",
    droppedAt: "2026-06-23",
    name: "Black Shiro - No Game No Life 1/7 Scale Figure",
    jan: "4570232588141",
    series: "No Game No Life",
    manufacturer: "Good Smile Company",
    type: "Scale",
    price_jpy: 27360,
    price_usd: 186,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 198,
    availability: "available",
    release_date: "2027-06-30",
    scale: "1/7",
    height: "26cm",
    featured: false,
    image_url: "/figures/black-shiro-no-game/thumb.jpg",
    images: [
      "/figures/black-shiro-no-game/01.jpg",
      "/figures/black-shiro-no-game/02.jpg",
      "/figures/black-shiro-no-game/03.jpg",
      "/figures/black-shiro-no-game/04.jpg",
      "/figures/black-shiro-no-game/05.jpg",
      "/figures/black-shiro-no-game/06.jpg",
    ],
  },
  {
    id: "79",
    droppedAt: "2026-06-23",
    name: "Nendoroid Mika Misono Swimsuit Ver. (Basic) Blue Archive Figure Limited Bonus Set",
    jan: "4570232585263",
    series: "Blue Archive",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 4890,
    price_usd: 33,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 60,
    availability: "available",
    release_date: "2026-11-30",
    scale: "Non-scale",
    height: "10cm",
    featured: false,
    image_url: "/figures/nendoroid-mika-misono-swimsuit/thumb.jpg",
    images: [
      "/figures/nendoroid-mika-misono-swimsuit/01.jpg",
      "/figures/nendoroid-mika-misono-swimsuit/02.jpg",
      "/figures/nendoroid-mika-misono-swimsuit/03.jpg",
      "/figures/nendoroid-mika-misono-swimsuit/04.jpg",
    ],
  },
  {
    id: "80",
    droppedAt: "2026-06-23",
    name: "B-Style Wendy Marvell: Bunny Ver. - FAIRY TAIL 1/4 Scale Figure",
    jan: "4570001515132",
    series: "Fairy Tail",
    manufacturer: "FREEing",
    type: "Scale",
    price_jpy: 36575,
    price_usd: 249,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 197,
    availability: "available",
    release_date: "2027-01-31",
    scale: "1/4",
    height: "42cm",
    featured: false,
    image_url: "/figures/b-style-wendy-marvell/thumb.jpg",
    images: [
      "/figures/b-style-wendy-marvell/01.jpg",
      "/figures/b-style-wendy-marvell/02.jpg",
      "/figures/b-style-wendy-marvell/03.jpg",
      "/figures/b-style-wendy-marvell/04.jpg",
      "/figures/b-style-wendy-marvell/05.jpg",
      "/figures/b-style-wendy-marvell/06.jpg",
      "/figures/b-style-wendy-marvell/07.jpg",
      "/figures/b-style-wendy-marvell/08.jpg",
    ],
  },
  {
    id: "81",
    droppedAt: "2026-06-23",
    name: "DLX Iron Man Mark 44 \"Hulkbuster\" (Battle Damaged) - Marvel Studios' The Infinity Saga 1/12 Action Figure",
    jan: "4595430617271",
    series: "Marvel: The Infinity Saga",
    manufacturer: "threezero",
    type: "Scale",
    price_jpy: 50160,
    price_usd: 341,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 197,
    availability: "available",
    release_date: "2026-12-31",
    scale: "1/12",
    height: "30cm",
    featured: false,
    image_url: "/figures/dlx-iron-man-mark/thumb.jpg",
    images: [
      "/figures/dlx-iron-man-mark/01.jpg",
      "/figures/dlx-iron-man-mark/02.jpg",
      "/figures/dlx-iron-man-mark/03.jpg",
      "/figures/dlx-iron-man-mark/04.jpg",
      "/figures/dlx-iron-man-mark/05.jpg",
      "/figures/dlx-iron-man-mark/06.jpg",
      "/figures/dlx-iron-man-mark/07.jpg",
      "/figures/dlx-iron-man-mark/08.jpg",
    ],
  },
  {
    id: "82",
    droppedAt: "2026-06-23",
    name: "MODEROID King's Style Winzert Plastic Model Reissue",
    jan: "4570232588103",
    series: "Mado King Granzort",
    manufacturer: "Good Smile Company",
    type: "Model Kit",
    price_jpy: 5832,
    price_usd: 40,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 200,
    availability: "available",
    release_date: "2026-12-31",
    scale: "Non-scale",
    height: "18cm",
    featured: false,
    image_url: "/figures/moderoid-king-s-style/thumb.jpg",
    images: [
      "/figures/moderoid-king-s-style/01.jpg",
      "/figures/moderoid-king-s-style/02.jpg",
      "/figures/moderoid-king-s-style/03.jpg",
      "/figures/moderoid-king-s-style/04.jpg",
      "/figures/moderoid-king-s-style/05.jpg",
      "/figures/moderoid-king-s-style/06.jpg",
      "/figures/moderoid-king-s-style/07.jpg",
      "/figures/moderoid-king-s-style/08.jpg",
    ],
  },
  {
    id: "83",
    droppedAt: "2026-06-23",
    name: "Nendoroid Red Pyramid Thing SILENT HILL 2 Figure Reissue",
    jan: "4570232588059",
    series: "Silent Hill 2",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 5934,
    price_usd: 40,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 194,
    availability: "available",
    release_date: "2026-11-30",
    scale: "Non-scale",
    height: "10cm",
    featured: true,
    image_url: "/figures/nendoroid-red-pyramid-thing/01.jpg",
    images: [
      "/figures/nendoroid-red-pyramid-thing/01.jpg",
      "/figures/nendoroid-red-pyramid-thing/02.jpg",
      "/figures/nendoroid-red-pyramid-thing/03.jpg",
      "/figures/nendoroid-red-pyramid-thing/04.jpg",
      "/figures/nendoroid-red-pyramid-thing/05.jpg",
      "/figures/nendoroid-red-pyramid-thing/06.jpg",
    ],
  },
  {
    id: "84",
    droppedAt: "2026-06-23",
    name: "Nendoroid Mococo Abyssgard Hololive Production Figure Limited Bonus Set",
    jan: "4570232588073",
    series: "Hololive Production",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 8590,
    price_usd: 58,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 52,
    availability: "available",
    release_date: "2026-11-30",
    scale: "—",
    height: "10cm",
    featured: false,
    image_url: "/figures/nendoroid-mococo-abyssgard-hololive/thumb.jpg",
    images: [
      "/figures/nendoroid-mococo-abyssgard-hololive/01.jpg",
      "/figures/nendoroid-mococo-abyssgard-hololive/02.jpg",
      "/figures/nendoroid-mococo-abyssgard-hololive/03.jpg",
      "/figures/nendoroid-mococo-abyssgard-hololive/04.jpg",
      "/figures/nendoroid-mococo-abyssgard-hololive/05.jpg",
      "/figures/nendoroid-mococo-abyssgard-hololive/06.jpg",
      "/figures/nendoroid-mococo-abyssgard-hololive/07.jpg",
      "/figures/nendoroid-mococo-abyssgard-hololive/08.jpg",
    ],
  },
  {
    id: "85",
    droppedAt: "2026-06-23",
    name: "Nendoroid Fuwawa Abyssgard Hololive Production Figure Limited Bonus Set",
    jan: "4570232588066",
    series: "Hololive Production",
    manufacturer: "Good Smile Company",
    type: "Nendoroid",
    price_jpy: 8590,
    price_usd: 58,
    retailer: "Hobby Genki",
    retailer_color: "blue",
    status: "preorder_open",
    quantity: 53,
    availability: "available",
    release_date: "2026-11-30",
    scale: "—",
    height: "10cm",
    featured: false,
    image_url: "/figures/nendoroid-fuwawa-abyssgard-hololive/thumb.jpg",
    images: [
      "/figures/nendoroid-fuwawa-abyssgard-hololive/01.jpg",
      "/figures/nendoroid-fuwawa-abyssgard-hololive/02.jpg",
      "/figures/nendoroid-fuwawa-abyssgard-hololive/03.jpg",
      "/figures/nendoroid-fuwawa-abyssgard-hololive/04.jpg",
      "/figures/nendoroid-fuwawa-abyssgard-hololive/05.jpg",
      "/figures/nendoroid-fuwawa-abyssgard-hololive/06.jpg",
      "/figures/nendoroid-fuwawa-abyssgard-hololive/07.jpg",
      "/figures/nendoroid-fuwawa-abyssgard-hololive/08.jpg",
    ],
  },
];

export function getFigure(id: string): Figure | undefined {
  return figures.find((f) => f.id === id);
}

/**
 * URL slug for a figure = its `public/figures/<key>/` folder key (already unique
 * per figure), parsed from the image path. This is the canonical product-URL
 * segment (`/drops/t/<slug>`); `id` stays the internal key (wishlist, redirects).
 */
export function figureSlug(f: Figure): string {
  const src = f.image_url || f.images[0] || "";
  const m = src.match(/\/figures\/([^/]+)\//);
  return m ? m[1] : f.id;
}

export function getFigureBySlug(slug: string): Figure | undefined {
  return figures.find((f) => figureSlug(f) === slug);
}

export function getFeatured(): Figure {
  return figures.find((f) => f.featured) ?? figures[0];
}

export function relatedBySeries(series: string, excludeId: string): Figure[] {
  return figures.filter((f) => f.series === series && f.id !== excludeId);
}

/** Parse a YYYY-MM-DD string as local midnight to avoid timezone day-shifts. */
export function parseDate(s: string): Date {
  return new Date(s + "T00:00:00");
}

export type StockLevel = "sold_out" | "last_items" | "low" | "in_stock";

/** Real stock state from HG's PrestaShop `quantity` / `availability`. */
export function stockLevel(f: Figure): StockLevel {
  if (f.quantity <= 0 || f.availability === "unavailable") return "sold_out";
  if (f.availability === "last_remaining_items" || f.quantity <= 3)
    return "last_items";
  if (f.quantity <= 20) return "low";
  return "in_stock";
}
